### ISSUE TITLE
[FEATURE REQUEST] - Add warning - File already exists do you want to overwrite

### ISSUE THREAD

**Issue by X3msnake** [sn4k3/UVtools#10]
As it is right now when you open a file and modify it,

If you click save the software instantly overwrites the file with the same name.

Best practice is the software asks if the use wants to overwrite  if you want to keep this method for the wild users you can add a config setting to suppress overwrite files check. but that should be something the user opts in

**Comment by brynnflynn** [comment]
Standard behavior is to just save the file in place when you click save, and if you use Save As, to allow you to define a new file name and save. Can you confirm which menu option you're referring to? I don't think it's appropriate to have such a prompt for "Save", but "Save As" would make sense.
