### ISSUE TITLE
[FEATURE REQUEST] Pixel dimming chamfer

### ISSUE THREAD

**Issue by RJSavell** [sn4k3/UVtools#106]
In the pixel dimming feature would it be possible to add a chamfer option?  for example something like this:

![image](https://user-images.githubusercontent.com/47092573/100550767-6d1bdf80-3239-11eb-988f-f378f5fbff7d.png)

For example if you wanted to modify the first 5 pixels from the edge inward for first 5 layers using a pattern such as this:
layer 0: 127 127 127 127 127
layer 1: 127 127 127 127 255
layer 2: 127 127 127 255 255
layer 3: 127 127 255 255 255
layer 4: 127 255 255 255 255

Thanks,

Randy

**Comment by sn4k3** [comment]
You cant use pattern to do chamfer as that would require whole image information as a pattern, by running so you would end with that pattern repeating across xy every 5 pixels.
Instead i can implement a chamfer like morph which acts over border thickness, so the input would be:

border size: 5 to 1 at 127 brightness

**Comment by RJSavell** [comment]
I tried the morph / erode and it seems to work but if that is something you could do and allow a brightness setting that would be even better.

Thanks!!!!

Randy

**Comment by sn4k3** [comment]
implemented

**Comment by RJSavell** [comment]
Thank you!
