### ISSUE TITLE
[BUG] Repair islands function ignores pixel setting

### ISSUE THREAD

**Issue by roofuskit** [sn4k3/UVtools#107]
## Describe the bug
Repair function ignores pixel settings for islands and repairs all islands regardless of size.

## To Reproduce
1. click issues
2. click repair
3. change "Remove islands equal or smaller to:" to 1 pixel
4. click repair.

## Expected behavior
Only islands consisting of a single pixel should be removed. 

## Screenshots
N/A

## Files
N/A

## System
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 x64 v20H2]
  
## Exceptions Log file
N/A

## Additional context
N/A

**Comment by sn4k3** [comment]
Hi, this worked for me.
My test: Draw single pixels islands, draw two pixel islands.
Use repair to remove all islands below or equal 1px. 
Result: 1px islands was removed, but 2px islands remanin untouched.

Before repair:
![image](https://user-images.githubusercontent.com/113281/100801303-b4fc5b80-341f-11eb-897e-28f28f0dae90.png)

After repair:
![image](https://user-images.githubusercontent.com/113281/100801346-c47ba480-341f-11eb-983f-8ca2fd8a7cb9.png)


Can you try this?

**Comment by sn4k3** [comment]
Everything looks to work as expected
