### ISSUE TITLE
[FEATURE REQUEST] Add mouse over pixel color information

### ISSUE THREAD

**Issue by X3msnake** [sn4k3/UVtools#113]
Add mouse over information about the pixel colour 
Similar to the colour drop sampler information. ideally it could just have the value display on the information bar as one moves the mouse over the pixels alternatively it could read using a key combo or as a tool

![image](https://user-images.githubusercontent.com/11083514/102488822-8bb90d80-4064-11eb-8df8-df4b0f1d4076.png)

**Comment by sn4k3** [comment]
UVtools already have a brightness picker (Layer status bar with coordinates and **B** of brightness).
Hold CTRL and hover on a pixel. Release CTRL to lock the selection.
See:

![image](https://user-images.githubusercontent.com/113281/102507680-7354ed00-407c-11eb-8df1-030e8def45e2.png)

**Comment by X3msnake** [comment]
Awsome i think we soon need to write a manual for this :P
