### ISSUE TITLE
[BUG] 2.1.0 - msi not creating desktop shortcut windows10

### ISSUE THREAD

**Issue by X3msnake** [sn4k3/UVtools#118]
- Update install did not create desktop shortcut
- Fresh install did not create desktop shortcut
- No icon thumbnail
- There is a popup window that stays open

![image](https://user-images.githubusercontent.com/11083514/103358816-6db0cb80-4aae-11eb-9daf-d6787cc727d0.png)

**Comment by sn4k3** [comment]
Fixed and reuploaded. Redownload the windows package.
