### ISSUE TITLE
Raising the build plate at the end of the print. 

### ISSUE THREAD

**Issue by Diterex** [sn4k3/UVtools#119]
Is there a way to add extra gcode to the end that makes the build plate go all the way to the top? I have a Mono X and there doesn't seem to be a great way to make this happen.

**Comment by sn4k3** [comment]
On GCode printers yes,  Mono X isn't one of them. 
Current firmwares are very limiting, and by source-closing them is even worst.
You best case is manual raize Z at printer LCD
