### ISSUE TITLE
[FEATURE REQUEST] Text Positioning 

### ISSUE THREAD

**Issue by mylife4aiurr** [sn4k3/UVtools#120]
## Is your feature request related to a problem? Please describe
When I press shift to place the text I don't know exactly how the text will be placed on the model. I only see a mouse crosshair only. This is not sufficient to know how big the text will be in relation to the model. Also, the cursor alone doesnt allow me to center text horizontally or vertically because I can't see the text before I actually click the cursor to place text. So currently I must place then clear, place then clear, until im happy.

## Describe the solution you'd like - quicker
Since currently, you must type the text in the text box prior to placing it on the model. Why not when pressing shift make an outline or shadow of the text with its chosen parameters. This way b4 user clicks for final placement, they'll know where it will be placed, the scale, the font type, and if it's aligned how they intend it to be.

**Comment by sn4k3** [comment]
implemented
