### ISSUE TITLE
[BUG] Installation path on update changed

### ISSUE THREAD

**Issue by taker218** [sn4k3/UVtools#121]
## Describe the bug
I installed the UVtools in another directory, rather then the standard one (program files). When I run an update it always populates the path with the standard one, not the one I installed the program before.

## To Reproduce
1. Install older version of UVtools to a non standard folder
2. Perfom update from the UVtools UI

## Expected behavior
I would have expected to have my current installation path in the update installer, not the standard one.

## Screenshots
<img width="386" alt="2021-01-04 15_56_16-UVtools Setup" src="https://user-images.githubusercontent.com/15029277/103548109-961d3900-4ea5-11eb-9266-3ff248602bb5.png">
<img width="363" alt="2021-01-04 15_56_46-Tools" src="https://user-images.githubusercontent.com/15029277/103548110-96b5cf80-4ea5-11eb-94cc-ae314c0185e2.png">

## Files
Were possible attach the problematic file, both source and output file if applicable.

## System
**Desktop (please complete the following information):**
 - OS: Windows 10 x64 20H2
  
## Exceptions Log file
In some unexpected exceptions errors will generate and save a log file under appfolder/Logs/AppErrors.
If present you can attach the log file here. Check file name against date/time to be sure it's related to your problem.

**Comment by sn4k3** [comment]
Each instalation is like a fresh install. The path is not saved on register and then no way to pull back the directory.
The msi wix is really a pain to work with...

**Comment by sn4k3** [comment]
Fixed, you need to remove uvtools, install with the new version and from now on it will save the path
