### ISSUE TITLE
Maximum island fix based on size

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#124]
I remember that the limit of 255 in "Remove islands equal or smaller than:" was because it might be destructive, but in big sculptures it does not make any sense, i.e.:

![image](https://user-images.githubusercontent.com/1091420/104459390-f51d3500-55ac-11eb-904c-29643310714a.png)

This Knight it is 13 cm height and since it was sculpted manually there is a lot of islands of 300-400 pixels that can be removed because they are just glitchy 2-3 layer triangles, so, again that arbitrary limit of 255 does not make any sense.

A limit based on the size of the object OR just leaving the user to decide higher values makes a lot more sense, the user already knows all the fix tool might be destructive.

**Comment by sn4k3** [comment]
255 is already huge, it's about 1.3cm, if you use it as no limit it can really make bad things on your model. As you said glitch masses can be removed but it will also remove everything else, with no iteration limit it can do a hole from bottom to top.
But if you find a good use for that values i can increase the limit to about 35k

**Comment by eried** [comment]
255 is an extremely tiny area:

![image](https://user-images.githubusercontent.com/1091420/104481625-4b4aa200-55c6-11eb-968f-cad8039e3eae.png)

anything sculpted may have some dangling features like that

**Comment by sn4k3** [comment]
Ok, i will increase the limit, is 65535 ok?
