### ISSUE TITLE
[BUG] uvtools crashes when trying to do a xyz calibration

### ISSUE THREAD

**Issue by mylife4aiurr** [sn4k3/UVtools#126]
## Describe the bug
Like the title. Uvtools crashes when attempting to use this save as base for uvtools calibration file.

## Files
https://drive.google.com/file/d/1u04tMyhFTOKkKSww2xVR755jhz9w1lpx/view?usp=sharing

## System
 - OS Windows 10
  
## Additional context
I have not used prusa slicer for a while. Save file was from an old version of Prusa slicer. All my clear resin profiles were done on prusa sl1. I looked for a prusa save file so uvtools could build a calibration model. 
Until fixed I'll make a new dummy save in new version of prusaslicer and report if crash still occurs.

**Comment by mylife4aiurr** [comment]
Doesn't happen with new prusaslicer v2.3.0 saves

**Comment by sn4k3** [comment]
Malformed file, prusaslicer.ini is missing

![image](https://user-images.githubusercontent.com/113281/104823328-45acc080-5841-11eb-8f8c-94c0a88ac894.png)

**Comment by mylife4aiurr** [comment]
Yea - old Prusa version save format. Came across it and letting you know , uvtools didnt like it. 

Long as user use current version of prusa slicer they'll never see this problem. Gonna close this
