### ISSUE TITLE
Profile install

### ISSUE THREAD

**Issue by MrCHarley** [sn4k3/UVtools#127]
On the Github page have followed word for word on "Install and configure profiles under PrusaSlicer"
How does one install the printer profiles to prusa slicer?? I've uninstalled, reinstalled and still these profiles do not show up in prusa slicer 2.3.0. At the point of giving up. 3 hours and getting no where with this.

**Comment by sn4k3** [comment]
Maybe you are using a alpha version of prusaslicer?
If don't what OS do you use?

**Comment by sn4k3** [comment]
closing, due lack of anwser
