### ISSUE TITLE
[BUG] XYZ accuracy test does not produce hollow model with walls

### ISSUE THREAD

**Issue by pesalek** [sn4k3/UVtools#128]
## Describe the bug
XYZ accuracy test does not produce hollow model with walls

## To Reproduce
Create XYZ accuracy test, hollow model tick box reacts in preview, but after generating, it is always a square with or without release hole. Not a square box with walls.

![image](https://user-images.githubusercontent.com/12142938/105345270-57e18280-5be4-11eb-892b-8738bf1d4fd3.png)

![image](https://user-images.githubusercontent.com/12142938/105345295-6039bd80-5be4-11eb-9958-71bbd8721183.png)

**Comment by sn4k3** [comment]
It works ok for me, preview shows you the last layer only, after generate you are showing the first layer which is solid due no relif hole, if you go up on layers you will get the walls
![image](https://user-images.githubusercontent.com/113281/105359402-510c3d00-5bef-11eb-9f5a-f60dd6ea0155.png)

**Comment by sn4k3** [comment]
closing, due lack of anwser
