### ISSUE TITLE
[BUG] PhotonS save error

### ISSUE THREAD

**Issue by lcoronelp** [sn4k3/UVtools#135]
## Describe the bug
Saved photons file doesn't recognized by PhotonS machine (neither open in Chitubox or UVTools)

## To Reproduce
1. Open Photons file exported from Chitubox
2. Execute Morph Erode 3/1 Chamfer: False Layers: Bottom
3. Save as PhotonS File
4.1. Try to print in PhotonS Machine -> Error: not recognized file
4.2. Try to open in Chitubox: show as [Fig. 1](#user-content-fig1) Only one triangle and don't calculate correct the time
4.3. Try to open in UVTools again: show as [Fig. 2](#user-content-fig2) Error in operation (overflow)

## Expected behavior
Print without problem

## Screenshots
<a id="fig1"></a>
![Captura de pantalla_2021-01-27_16-06-52](https://user-images.githubusercontent.com/1972410/106018875-e9a43080-60b9-11eb-9a8e-4e0048e9a974.png)
[Fig. 1]

<a id="fig2"></a>
![Captura de pantalla_2021-01-27_16-28-51](https://user-images.githubusercontent.com/1972410/106021592-dcd50c00-60bc-11eb-8298-bdd714713a58.png)
[Fig. 2]

## Files
[Gatitos.zip](https://github.com/sn4k3/UVtools/files/5881468/Gatitos.zip)
Chitubox Project

[Gatitos.zip](https://github.com/sn4k3/UVtools/files/5881466/Gatitos.zip)
File Exported from Chitubox

[GatitosEroded.zip](https://github.com/sn4k3/UVtools/files/5881473/GatitosEroded.zip)
File saved from UVTools after eroded

## System
 - OS: Linux Xubuntu 20.04 XFCE
 - Printer: PhotonS V5.0.2, UI 2.6
  
## Errors when opened in UVTools again
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at UVtools.Core.FileFormats.PhotonSFile.Decode(String fileFullPath, OperationProgress progress) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\FileFormats\PhotonSFile.cs:line 502
   at UVtools.WPF.MainWindow.<>c__DisplayClass95_0.<ProcessFile>b__0() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 921
```

Thanks Tiago! If you need more info or test something, não ha problema, é só dizer :)

**Comment by sn4k3** [comment]
PhotonS is not write-supported by UVtools. Is a read-only format.
You should use pws instead

**Comment by lcoronelp** [comment]
Thanks for the fast response!

Then i have two problems:
- When i open the PhotonS file in UVTools, i can't save to pws (only photons)
- Chitubox doesn't export in pws
- The convert function in UVTools doesn't work (i think is not implemented yet not?)

Know some workflow to use Chitubox and UVtools to make PWS files?

Thanks again!

**Comment by sn4k3** [comment]
Open the photons on UVtools, go to File -> Convert -> PhotonS (PWS)

**Comment by lcoronelp** [comment]
Convert as you say doesn't do anything (nor shows error)

Have some log that can i check?

**Comment by sn4k3** [comment]
Can you send me your photons file? use wetransfer and put the link here

**Comment by lcoronelp** [comment]
Video of trying to convert:
https://user-images.githubusercontent.com/1972410/106024584-d4ca9b80-60bf-11eb-977c-7e9d50d70aff.mp4

The .photons is in the bug report in a zip. https://github.com/sn4k3/UVtools/files/5881466/Gatitos.zip

The version of uvtools is 2.3.2 X64

Thanks!

**Comment by sn4k3** [comment]
Works for me, this is the output:
[Gatitos (2).zip](https://github.com/sn4k3/UVtools/files/5881758/Gatitos.2.zip)

If you try to convert to ctb, does it works?

**Comment by lcoronelp** [comment]
Didn't work, the convert menu doesn't work at all

And i note now than if i move the mouse in the menu, it closes immediately.
https://user-images.githubusercontent.com/1972410/106026229-79011200-60c1-11eb-9fd1-85cd75c772d3.mp4

Some bad interaction with the below preview? I note also that is not showing correctly

I have Nvidia GeForce GTX 1080 with OpenGL ES 3.2 NVIDIA 450.102.04

Curious.

**Comment by sn4k3** [comment]
What OS?

**Comment by sn4k3** [comment]
Try this build: https://we.tl/t-5xPqoU3Gp0

**Comment by lcoronelp** [comment]
Ok this version works as expected (is this a Qt version?)

The preview keeps rendering badly (but is a minor bug)
And sometimes it closes unexpectedly (two times making different actions)

Thanks for the help!

**Comment by sn4k3** [comment]
Not Qt, this is AvaloniaUI. A recent framework, and yes, it have some bugs, but as they release new versions is getting better. Windows have the least bugs.
I also notice that light desktops are worst with it, gnome seens more solid with this ui framework

**Comment by lcoronelp** [comment]
Great! i didn't know it!
If you need test or anything that i can do, tell me!

Thanks again! Your work in this app is amazing!

**Comment by sn4k3** [comment]
Can you send a screenshot of how main window and other window (for example Tool - Morph) look on your os? The patch i send you i have redesigned the UI.

**Comment by lcoronelp** [comment]
![Captura de pantalla_2021-01-27_17-39-24](https://user-images.githubusercontent.com/1972410/106031005-a00e1280-60c6-11eb-86ce-fd66b0f8d5b5.png)
![Captura de pantalla_2021-01-27_17-38-35](https://user-images.githubusercontent.com/1972410/106031007-a0a6a900-60c6-11eb-894f-1febbd907fdc.png)
![Captura de pantalla_2021-01-27_17-38-22](https://user-images.githubusercontent.com/1972410/106031008-a13f3f80-60c6-11eb-921a-4fdd98d27054.png)

**Comment by lcoronelp** [comment]
![Captura de pantalla_2021-01-27_17-44-32](https://user-images.githubusercontent.com/1972410/106031640-67226d80-60c7-11eb-915d-60ff33cc793f.png)
Repair error process

**Comment by sn4k3** [comment]
Looks sharp, only that message box still have hidden text :(

**Comment by lcoronelp** [comment]
The size of the message box is automatic? or calculated by the inner text?

If i resize it, the next times, it keeps extended
![Captura de pantalla_2021-01-27_17-54-28](https://user-images.githubusercontent.com/1972410/106032719-be750d80-60c8-11eb-8f6e-e153851fe578.png)

**Comment by sn4k3** [comment]
Automatic and limited to screen size, but sometimes it line breaks and clip words. It's a bug on the control and also happen with windows os

**Comment by lcoronelp** [comment]
Ouch. bugs bugs bugs everywhere xD

Im web developer, in Avalonia don't have something similar to white-space:nowrap? I thing that this message is short (or break in two lines always?) Sorry if you was tried this yet :P

**Comment by sn4k3** [comment]
It's really a problem on controler. It should wrap automaticly if needed, but all i see it dont need to wrap still it line break without a motive, worse, it clips the text. I already open a issue on controler but no response so far. But yes this framework have lot of bugs to fix, if you go to thier github the issues are flood. But they are in good path

**Comment by lcoronelp** [comment]
Sorry for the late answer. I was working (you know).

I see that Avaloina have only few months! But with a great and fast progress!

I like ask you, I can pass some option to the executable UVTools or something to obtain debug info to send to you? (because it's closing unexpectedly in random points)

**Comment by sn4k3** [comment]
It dont generate debug info. All you can do is execute from terminal and when it crash see if it return any message to the terminal

**Comment by lcoronelp** [comment]
Only
```
1193721 segmentation fault  ./UVtools
```

Checking a top i can see multiple process in hierarchy.
![Captura de pantalla_2021-01-27_21-33-14](https://user-images.githubusercontent.com/1972410/106057572-1111f200-60e8-11eb-97f6-cbf433c3ad6b.png)

Inclusive after the segmentation fault without any UVTools windows open :O
![Captura de pantalla_2021-01-27_21-37-29](https://user-images.githubusercontent.com/1972410/106057577-13744c00-60e8-11eb-8fac-9d266b110a92.png)

**Comment by sn4k3** [comment]
you can try to compile the libcvextern on your system and replace by yours, it can be...

**Comment by lcoronelp** [comment]
Compiling.

By the way, unfortunately neither the pws exported by the latest version nor the one you sent me work on Anycubic PhotonS :(

The machine show "File format error" when i touch play button.

**Comment by sn4k3** [comment]
You need to update your printer firmware

**Comment by lcoronelp** [comment]
I have the newest firmware 5.0.2, i can print correctly any pws exported with Photon workshop

**Comment by sn4k3** [comment]
Can you try slice by PrusaSlicer with my printer installed? Maybe the convertion from PhotonS lack of important parameters

**Comment by lcoronelp** [comment]
I will try (i currently don't have PrusaSlicer installed)

BTW, compiled and copied the libcvextern.so.

The preview keeps rendering badly
The app keep closing unexpectedly

:(

I send to you my libcvextern.so if it works for other: Xubuntu 20.04 https://we.tl/t-r6FnwzLHBn

**Comment by lcoronelp** [comment]
Hi again, i installed PrusaSlicer but i had some problems:

- UVtools only find the Prusa Slicer folder at `%HOME%/.PrusaSlicer` instead `%HOME%/.config/PrusaSlicer` defined in Prusa Slicer 2.3.0

- I make an `ln -s ~/.config/PrusaSlicer ~/.PrusaSlicer` and the UVTols recognize the folder correctly

- In my version (Avalonia) the buttons "unselect all" and "select all" in profiles didn't work

- Exporting from PrusaSlicer and importing in UVTools, the pws file works perfectly and is recognized by the printer without problem.
I think that the problems is in the conversion from Chitu .photons to .pws

- I noticed that the preview of file from PrusaSlicer work corretly, the Chitubox file don't.

I hope this can be useful!

**Comment by lcoronelp** [comment]
Hi again, I can see that my version of UVTools is very inestable:

With the same file (exported with same config from PrusaSlider), sometimes imports correctly and sometimes closes unexpectedly.

Can be because the avalonia version?

**Comment by lcoronelp** [comment]
I testing ten times the same file in non Avalonian (gtk?) version (official version) and don't close any moment. ;)

**Comment by lcoronelp** [comment]
Some interesting detail if that the avalonian version, the texts are bigger than the official version
![Captura de pantalla_2021-01-30_13-13-26](https://user-images.githubusercontent.com/1972410/106357274-0d0aed80-62fd-11eb-905d-5c7840f9804c.png)
Left: Avalonian
Right: Official

**Comment by lcoronelp** [comment]
Another thing:

In PrusaSlicer Printer Notes if i don't add `LiftSpeed_120` and only keep the `LiftingSpeed_120`, then the UVTools don't recognize the lifting speed and say (i think the default) 100mm/min

Additional, i can add `BottomLiftSpeed_65` to add the bottom lift speed (as Chitubox), and this config show correctly on UVTools for bottom layers.

I don't see any list of custom properties in the readme, do you have some info about that?

Thanks!

**Comment by sn4k3** [comment]
> Hi again, i installed PrusaSlicer but i had some problems:
> 
> * UVtools only find the Prusa Slicer folder at `%HOME%/.PrusaSlicer` instead `%HOME%/.config/PrusaSlicer` defined in Prusa Slicer 2.3.0
> * I make an `ln -s ~/.config/PrusaSlicer ~/.PrusaSlicer` and the UVTols recognize the folder correctly
> * In my version (Avalonia) the buttons "unselect all" and "select all" in profiles didn't work
> * Exporting from PrusaSlicer and importing in UVTools, the pws file works perfectly and is recognized by the printer without problem.
>   I think that the problems is in the conversion from Chitu .photons to .pws
> * I noticed that the preview of file from PrusaSlicer work corretly, the Chitubox file don't.

Thanks for the report i will work on that. 
In any case you should not use chitubox with photons since it have no AA and incomplete file info.
You can use chitubox if you create a custom printer and use Zip or ctb format and then convert with UVtools.

> With the same file (exported with same config from PrusaSlider), sometimes imports correctly and sometimes closes unexpectedly.
> Can be because the avalonia version?

Both are avalonia, the diference is one is the RC1 version and the last i sent you is the v1 "stable"
As told this UI have some bugs and can be unstable under some desktops, if you can try gnome i guess your problems will gone.

> Some interesting detail is that in the avalonian version, the texts are bigger than the official version

I retouched the GUI, thats why.

> In PrusaSlicer Printer Notes if i don't add LiftSpeed_120 and only keep the LiftingSpeed_120, then the UVTools don't recognize the lifting speed and say (i think the default) 100mm/min

Oh, i miss that one, it should be LiftSpeed_xxx will fix it next version.
Printer notes already show all compatible variables with the format, but you can find them here:
https://github.com/sn4k3/UVtools#custom-printer-notes-keywords-for-prusaslicer

**Comment by lcoronelp** [comment]
Thanks for the info Tiago!

If you need test something in no Gnome environment (XFCE with nvidia card) and/or PhotonS machine or some other test that you may need and you think i can do it, only write me.

Keep in touch!

**Comment by lcoronelp** [comment]
I see another small thing (do you prefer that i submit another bug when i found some detail? or we talk in another space? or i can mix all here?)

When import SL1 into UVTools, if the file have an dot `.`, then the PWS exported is trimmed at this point (probably the slice function is slicing for the first dot instead the last or the regex is not working as expected :D)

**Comment by sn4k3** [comment]
That problem is already fixed on current dev. Thanks for tell me back

**Comment by yaroslaw** [comment]
I have exactly same issues with printer not recognizing PWS after UVTools (win64). If it's fixed, where can I get the latest binaries?

**Comment by sn4k3** [comment]
> I have exactly same issues with printer not recognizing PWS after UVTools (win64). If it's fixed, where can I get the latest binaries?

Also converted from photons?

**Comment by yaroslaw** [comment]
Yeap. Sliced in Chitubox (both 1.8 beta and then 1.7 to confirm). First
tried to save a photons (there's no clue it shouldn't work in an app, and
it tries to save things), then saw a .pws export so used it also. Preview
picture is corrupted every time, and printer (5.0.2 updated) says it
doesn't recognize file format.

Also (tried only one model) in trying to fix resin traps it made perfectly
good hollow model with a drain hole completely "unhollow". Do you need a
model.photons for troubleshooting?

ср, 3 лют. 2021, 22:33 користувач Tiago Conceição <notifications@github.com>
пише:

**Comment by sn4k3** [comment]
As said on this topic, uvtools don't fully support PhotonS file format, is for read-only, any attempt to write or convert will fail. You need to slice to PWS on slicer, If you fully read this topic from begin you will find the same problem and "resolution" which is: dont use photons as source

**Comment by yaroslaw** [comment]
Chitubox don't have an option to export to any other format then .photons
for PhotonS. Is there a workaround you suggest?

Thanks!

чт, 4 лют. 2021, 21:05 користувач Tiago Conceição <notifications@github.com>
пише:

**Comment by sn4k3** [comment]
If you want to use chitubox you need to create a custom printer and coping same properties from photons. Then you can export to zip and convert with uvtools to pws.
Or use prusaslicer or lychee

**Comment by yaroslaw** [comment]
Thanks, I'll check it out.

**Comment by sn4k3** [comment]
PhotonS still readonly, a error will pop if anyone try to write a photons file.
