### ISSUE TITLE
[BUG] linux location of prusaslicer profiles

### ISSUE THREAD

**Issue by cubiq** [sn4k3/UVtools#136]
PrusaSlicer now follows a better standard for saving configuration files and as a result the option to import prusaslicer profiles fails. Old location is ~/.PrusaSlicer, new location is ~/.config/PrusaSlicer/. The solution might be to search first on the latter and if it fails on the former, or let the user choose the directory.

As a temporary solution you can symlink the directory.

**Comment by sn4k3** [comment]
Already fixed on current dev. Thanks for reporting

**Comment by sn4k3** [comment]
Fixed
