### ISSUE TITLE
[BUG] Extraction fails on pwmx file

### ISSUE THREAD

**Issue by Fevix** [sn4k3/UVtools#140]
## Describe the bug
Extraction fails when trying to extract a .pwmx file.

## To Reproduce
1. Open a .pwmx file
2. File >Extract

## Expected behavior
The images appear in the selected folder

## Screenshots
![image](https://user-images.githubusercontent.com/1657108/107540401-0188b380-6b94-11eb-9637-dbbc687cd50b.png)

## System
**Desktop (please complete the following information):**
 - OS: Windows 10 build 1909
  
## Exceptions Log file
None (unless I'm looking in the wrong location)

**Comment by sn4k3** [comment]
Will fix on next patch. Thank you

**Comment by sn4k3** [comment]
Fixed
