### ISSUE TITLE
[BUG] Bug in time calculation for VLH + CTRL Z crash

### ISSUE THREAD

**Issue by Nume1977** [sn4k3/UVtools#150]
## Describe the bug
If i make a variable layer height of minimum 0.1mm / max 0.2mm with linear steps of 1s for the itineration's, the resulting time at the end does not change, but the fact is I can do the print it in about 5H (-3H)

![Untitled](https://user-images.githubusercontent.com/26676082/108244893-9a48a180-7147-11eb-8fe0-7c9ebd66590b.png)

Also, executing "undo" after vlh will crash UVTools :P

**Comment by sn4k3** [comment]
I will check that.
Also Undo this operation is very aggressive

**Comment by sn4k3** [comment]
Works for me, undo as well.
![image](https://user-images.githubusercontent.com/113281/108249229-b733a380-714c-11eb-970e-9e5fd474012d.png)

What file format you are using?

**Comment by Nume1977** [comment]
I am using PrusaSlicer 2.3.0 (with the Nova3d printer installed from UVtools) to save a sl1 file for nova3D (cws).
I have just sliced a fresh stl, using the printer profile and universal 0.035 and always have the same result when doing VLH on UVTools...

Maybe it has something to do with the file type (CWS)?

![Untitled](https://user-images.githubusercontent.com/26676082/108252394-7c336f00-7150-11eb-8d8a-dabed567e048.png)

**Comment by sn4k3** [comment]
Never use more than 2 decimals for layer height! 0.xx max!
I dont have universal 0.035 profiles... please check that

**Comment by Nume1977** [comment]
Sorry my typo, I meant 0.03mm!

**Comment by sn4k3** [comment]
If you have them by a old version, please delete them

![image](https://user-images.githubusercontent.com/113281/108252847-02e84c00-7151-11eb-9643-e01264b05a34.png)

**Comment by sn4k3** [comment]
Ok just tried with a cws, still work for me, both print time and undo...
Can you send me your file?

**Comment by Nume1977** [comment]
Weird!
I am sending a 0.2mm sliced SL1 (0.05 is over 100Mb!)
[FalconWith_Landing_Gear_0.2mm.sl1.zip](https://github.com/sn4k3/UVtools/files/5997972/FalconWith_Landing_Gear_0.2mm.sl1.zip)

**Comment by sn4k3** [comment]
ok i found the problem, is due the auto convertion from sl1 to cws. After open the sl1 if you refresh (Ctrl + F5) it will work

**Comment by Nume1977** [comment]
CTRL + F5 fixes the issue!

**Comment by sn4k3** [comment]
Fixed
