### ISSUE TITLE
[BUG] Print time calculation

### ISSUE THREAD

**Issue by Nume1977** [sn4k3/UVtools#151]
## Describe the bug
After changing "Exposure time" in print parameters, the Print time remains the same of the original file (never gets recalculated), and there is a bug on edit box, it displays the original time.

## To Reproduce
1. Go to 'Edit print parameters'
2. Click on 'Exposure time' and change value
3. Accept
4. Goto step 1 to see 'Exposure time', it returned to the original value

**Comment by sn4k3** [comment]
Works for me xD
Please complete with file format

**Comment by Nume1977** [comment]
LOL!
Comecei pela versão portable (Zip), mas depois tive que apagar a diretoria e instalar a 2.4.0 através do msi e a partir daí só usei o auto-update... Será configs das versões antigas que não foram apagados!? Onde posso apagar?
Acho que todos os problemas vêm daí ...

**Comment by sn4k3** [comment]
Keep talks in english only.
MSI have problems, i recommend to uninstall first then install.
The configuration files have nothing to do with this problem, again the problem should come from the auto converted file, CTRL + F5 should also solve that

**Comment by Nume1977** [comment]
CTRL + F5 fixes the issue!

**Comment by sn4k3** [comment]
After auto convertion always use the .cws, if you reopen the .sl1 by mistake the .cws will be overwritten

**Comment by Nume1977** [comment]
Will do, thanks mate!
