### ISSUE TITLE
[BUG] Morph window resizes wrong amount when kernel options are expanded

### ISSUE THREAD

**Issue by tofof** [sn4k3/UVtools#152]
## Describe the bug
When the kernel options are expanded open in the morph window, the morph window resizes to accomodate the extra stuff. However, it doesn't get enough larger, and the OK / Cancel buttons end up mostly cut off.

## To Reproduce
1. Morph window
2. Click on Kernel options - expand

## Expected behavior
The morph window just needs to get another 50ish px larger than it currently does.

## System
* OS: Win 10 Pro x64 1803
* UVtools 2.4.8

Tons of updates recently! Keep up the great work but don't work too hard!

**Comment by sn4k3** [comment]
I guess this is on scaling > 100% ?
This is not UVtools related, but the UI framework have tons of bugs in that way, lets wait and hope they fix most of then on coming releases

**Comment by tofof** [comment]
No, normal 100% scaling on a 1920x1080.

The setting "take into account the screen scale factor to limit the dialogs windows maximum size" has no effect on this behavior.

![Untitled](https://user-images.githubusercontent.com/3980843/108418369-c2430e00-71f6-11eb-9922-2cb121b34be4.png)

**Comment by tofof** [comment]
Possibly related - in the settings dialog, the miscellaneous tab can't be scrolled all the way to the bottom unless I click into the 'issues' tab first, which gets the 'save/cancel' bar to show up and then I can scroll all the way down.

![Untitled](https://user-images.githubusercontent.com/3980843/108419111-be63bb80-71f7-11eb-99fe-a92bcdcfc888.png)

**Comment by sn4k3** [comment]
Thats strange, because on my same resolution as you shows all 
![image](https://user-images.githubusercontent.com/113281/108419470-7742ee00-722a-11eb-8e6b-aba80efe0630.png)

Post screenshot of F1 dialog

**Comment by tofof** [comment]
![image](https://user-images.githubusercontent.com/3980843/108419681-76916400-71f8-11eb-812c-5e71a588fb3f.png)

**Comment by sn4k3** [comment]
Ok nothing to flag on that about box. Its just strange why works on my but on others dont... My even work with 175% scale without cuts

**Comment by tofof** [comment]
Yup, weird. I believe you that it's a problem for the ui framework, though, so I'm going to close this.

**Comment by sn4k3** [comment]
It is, i already have to apply some hacks for windows to show up "correctly", i will not keep wasting time on this since this must be fixed on core and should be a painless thing to deal with
