### ISSUE TITLE
Issue detection breaks when Islands [YES] + Overhangs [NO]

### ISSUE THREAD

**Issue by tofof** [sn4k3/UVtools#177]
## Description
When settings are to compute islands but not overhangs, issue searches do not execute at all.

## To Reproduce
1. Settings -> Issues -> Islands [:heavy_check_mark:], Overhangs [&nbsp;&nbsp;&nbsp;]
2. Save, restart, detect issues (automatically or manually depending on other settings). Nothing happens.

## Other Information
Setting `Enhance island detection with an combined overhang check` does not influence bugged behavior.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Trivial / Localization - that setting should use "a", not "an")

Islands [&nbsp;&nbsp;&nbsp;] / Overhangs [:heavy_check_mark:] works as expected. 
Islands [&nbsp;&nbsp;&nbsp;] / Overhangs [&nbsp;&nbsp;&nbsp;] works as expected. 
Islands [:heavy_check_mark:] / Overhangs [:heavy_check_mark:] works as expected.

[usersettings.zip](https://github.com/sn4k3/UVtools/files/6240761/usersettings.zip) contains working and nonworking usersettings.xml files.

## Expected behavior
Islands check functions independently from overhang check as in prior versions.
(Known good behavior in 2.4.8).

## System
* OS: Win 10 Pro x64 20H2 19042.867
* UVtools 2.7.0, 2.7.2

**Comment by sn4k3** [comment]
Works for me on the DEV version
![image](https://user-images.githubusercontent.com/113281/113241328-60220200-92a6-11eb-8857-952b0164679d.png)

I will check on that version to see if is fixed now

**Comment by tofof** [comment]
> EDIT: To bug happens, touching bounds and empty layer must also be disabled...
FWIW, empty layer setting doesn't change the behavior for me, but you're right that touching bounds must be disabled.

**Comment by sn4k3** [comment]
> FWIW, empty layer setting doesn't change the behavior for me, but you're right that touching bounds must be disabled.

Yep, a lacking of parentheses on the spare cycle condition. WIll be fine on next patch.
Thanks for reporting
