### ISSUE TITLE
Calibration Exposure Creating Faulty Layer at interface [BUG] 

### ISSUE THREAD

**Issue by dgm3333** [sn4k3/UVtools#188]
The calibration test is not creating consistent feature sizes at different layers as per the following (first) screenshot.
This is sliced with 0.1mm layer height with 4 bottom layers and a *base height of 0.3* (under the object configuration) showing the layer at the interface (too thin) and the one above (OK). Similar occurs with layer height of 0.15 and base 0.3 (haven't tested others)
The error isn't present when slicing 0.01 layer height or 0.1 with 0.4mm base height or the standard 1mm base. 

Also I don't think the following is a bug with UVTools calibration, but at 0.01mm with base height of 1mm my exposure tester prints for most of the letters, are failing to adhere at that interface (for all exposures), so there's another issue I haven't figured out yet. Slower lift speed didn't help either but it did get me wondering if a lift speed calibration option would be helpful?
Below is the latter issue - which is happening over a wide range of exposures and a number of different prints, including at the point which would seem to be optimal exposure from the features which are retained (and which typically work for me and community).

![image](https://user-images.githubusercontent.com/51210/115951937-4fe2f880-a4db-11eb-89a4-242a4a279c78.png)

![image](https://user-images.githubusercontent.com/51210/115955629-a9edb900-a4ef-11eb-8242-7e663ff06caa.png)

**Comment by sn4k3** [comment]
It looks like you are using erodes? Can you post a screenshot of the values you use on the dialog?

**Comment by dgm3333** [comment]
If I am using erodes I'm not aware of it, and the Erode Bottom setting is definitely 0. Is there anywhere else it would be set?
As noted the "erosion" doesn't occur with 1mm base thickness although all other settings were identical.
I'm unlikely to actually print the test any more since it isn't working for me.

![image](https://user-images.githubusercontent.com/51210/115972588-32e40f00-a547-11eb-9bce-e0d3069116b5.png)

**Comment by sn4k3** [comment]
The Chamfer layers is also an erode, so you have 5 chamfered layers, it will cath layer 4 and 5 with features, set that to 3 or 0
