### ISSUE TITLE
[BUG] Elegoo Mars Pro profile not working

### ISSUE THREAD

**Issue by GuillaumeRives** [sn4k3/UVtools#19]
**Describe the bug**
I don't know if it's a bug or a my misunderstanding but I have an Elegoo Mars Pro so I imported the Elegoo Mars 2 Pro profile into PrusaSlicer. When I try to print a model with this profile, my printer tell me the screen dimensions are mismatching. I tried with the Elegoo Mars profile and it works since those two printers have the same screen dimensions.

**Expected behavior**
Is this Elegoo Mars 2 Pro profile intended to cover the Elegoo Mars Pro or a new Elegoo Mars printer I'm still unaware of ?
To avoid misunderstanding, I suggest to add a new profile import choice named Elegoo Mars Pro with its real caracteristics.
![image](https://user-images.githubusercontent.com/11697801/89888242-ec749d00-dbcf-11ea-9e43-7dd4a9d61f7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 v2004

**Comment by sn4k3** [comment]
You have done a a new printer into PrusaSlicer? If so you need implement some stuff into Notes. 
The easy way is use UVtools printers: go to UVtools Help -> Install Printers into PrusaSlicer
![image](https://user-images.githubusercontent.com/113281/89907446-9c540580-dbe4-11ea-9a52-aa07ef6c582c.png)

**Comment by GuillaumeRives** [comment]
Ok, so it was a misunderstanding from me then. I used the standard Elegoo Mars profile and it works great !
