### ISSUE TITLE
[BUG] Calculator bottom light off delay does not work proper

### ISSUE THREAD

**Issue by gessima** [sn4k3/UVtools#193]
## Describe the bug
Calculator tool bottom light off delay does not work proper - set parameters on file is taking wrong parameters (from normal light off delay)
## To Reproduce
1. Go to 'Tools'
2. Click on 'Calculator'
3. Click on "light off delay"
3. Scroll down to 'Set parameters to file'

## Expected behavior
When setting 15sec to "bottom light off delay" and pressing button "set parameters to file" it takes the other parameter set in "light off delay"

**Comment by sn4k3** [comment]
Works for me... What is your printer?

**Comment by gessima** [comment]
I did not put the file to my printer - have just seen on the screen that the values are not taken correctly.  I load a file and in the bottom line there is the information Light off 1s/1s .  When I go to tools/calculator/Light off delay then I can choose to set the light off delay (left hand button) - or set the bottom light off delay (right hand button) . Now I set a value of 5s for the normal light off delay (left side) and a value of 10s for the bottom light off delay (right side) - and when I press now the left button to set the parameter to file (5s) I can see that the value in the file information that was before 1s/1s now is changing to 1s/5s . Seems to be be maybe correct.....When I press the right button to set the parameter to file (10s - for the bottom) the file information is changing to 5s/5s - and this is wrong !? Should be 10s/5s ??

**Comment by gessima** [comment]
I have at work Anycubic Mono X and at home Anycubic Zero

**Comment by sn4k3** [comment]
AnyCubic series don't have bottom* properties just the normal.
UVtools repeat the value from normal to show the bottom, and if you try to set the bottom it sets to the normal to keep compability with the program logic.

![image](https://user-images.githubusercontent.com/113281/117542183-822e4300-b00f-11eb-90f0-fccd061a5f37.png)

Note that's a firmware lacking of that settings and you can't have different settings for bottom beside the exposure time.
If you open the Edit print paramaters it will show you all the avaliable properties in the format to change.

Still i should disable bottom inputs at calculator if unable to, i will improve that
