### ISSUE TITLE
[BUG] Elegoo Mars profile does not work

### ISSUE THREAD

**Issue by darraghbr** [sn4k3/UVtools#20]
The Elegoo Mars profile does not appear to output correct parameters for the sliced file. 

The exported .sl1 file from PrusaSlicer looks fine when imported into UVtools, and the file looks fine when converted to .cbddlp and imported to UVtools, but when that file is imported into ChiTuBox the displayed geometry does not look correct. The file prints fine, but the geometry appears stretched.

**To Reproduce**

1. Slice a model in PrusaSlicer using the UVtools Elegoo Mars profile
2. Export .sl1 file from PrusaSlicer
3. Import .sl1 file into UVtools
4. In UVtools convert the .sl1 file to .cbddlp
5. Import the .cbddlp file into ChiTuBox

**Expected behavior**

I expect the geometry on the imported file to be consistent with the sliced information.

**Screenshots**

![image](https://user-images.githubusercontent.com/31858409/89978067-930a7d80-dc64-11ea-984f-b8034090c6c5.png)

This is the model in PrusaSlicer. 

![image](https://user-images.githubusercontent.com/31858409/89978104-a74e7a80-dc64-11ea-885b-3cd1a03812f4.png)

And this is the model when imported into ChiTuBox. As you can see the model has been stretched. 

**Files**

I have used the Ameralabs Town calibration part.

**Desktop (please complete the following information):**

Windows 10 build 19041

**Comment by sn4k3** [comment]
Many people are afraid of this, but not really a problem, it's all good.
Please check this recent open issue: https://github.com/sn4k3/UVtools/issues/18

**Comment by darraghbr** [comment]
Ok, that is a very strange bug...

**Comment by darraghbr** [comment]
Re opened after editing issue to reflect it is just an appearance issue.
