### ISSUE TITLE
[BUG] BigSur tool windows content not scrollable

### ISSUE THREAD

**Issue by brettvitaz** [sn4k3/UVtools#201]
## System
 - OS: Mac OS 11.3.1 (Big Sur)
 - Slicer: Lychee
 - Printer: Elegoo Saturn

## Describe the bug
Calibration tools windows are not resizable and some content cannot be accessed. 

## To Reproduce
1. Click "Calibration" menu.
2. Select item "Elephant Foot".
3. Elephant foot window is fixed in size and items on the right are invisible and unaccessible.

## Expected behavior
Window should fit content, or allow scrolling.

## Screenshots
<img width="1792" alt="Screen Shot 2021-05-15 at 9 31 25 AM" src="https://user-images.githubusercontent.com/7563757/118371231-7a672500-b560-11eb-8170-c312fe3c8acc.png">

**Comment by sn4k3** [comment]
BigSur was wrong information to framework. Go settings and disable this: 
![image](https://user-images.githubusercontent.com/113281/118371398-67764400-b5a4-11eb-8c52-5bb5783c8ad7.png)

**Comment by brettvitaz** [comment]
Thank you for the quick response. I have also noticed that the underlying issue causes problems attempting to resolve the issue as seen in this screenshot:

<img width="1792" alt="Screen Shot 2021-05-15 at 12 33 18 PM" src="https://user-images.githubusercontent.com/7563757/118375940-da1dfa00-b579-11eb-93ed-78861f026c98.png">

The "Save Settings" button is not shown unless you navigate to one of the other settings tabs. Switching to the "Layer Preview" tab and back caused the Save button to appear.

**Comment by sn4k3** [comment]
Yeah you can also hit ENTER.
Does it solve your problem?

**Comment by brettvitaz** [comment]
Yes. The issue is resolved. Thank you

**Comment by brettvitaz** [comment]
As I mentioned, my original issue is resolved, but I did some additional testing and noticed that hitting "Enter" toggles the state of the selected option, and does not save the settings. 

Note: Clicking on the tab title after setting the appropriate selection allows the user to then hit "Enter" to save, but I would not consider this an obvious course of action.

**Comment by sn4k3** [comment]
Enter will not work on inputs where it can accept enter to do an action, eg: Open dropdown, OR in a text input with multiple lines where you need enter to do a line break. You need to click on window background so it gain focus and then ENTER will work.
This is not a bug with UVtools, but apple doing it's magic and reporting bad information about resolution

**Comment by brettvitaz** [comment]
I completely understand this and have dealt with comparable limitations when developing user interfaces. I appreciate all of the work put into UVTools and I am only hoping to make it easier for other people who find the same issue to resolve.

While perhaps not a bug, it is a user experience problem that is present in UVTools software. If this project allows external contribution, I would be happy to look into ways to mitigate the issue.

**Comment by sn4k3** [comment]
UVtools is open source, you can always fork it and modify.
The only way to fix this is auto disable that setting when detecting a macOS bigSur or greater
