### ISSUE TITLE
[BUG] Windows Defender flags UVtools as Trojan:Win32/Emali.A!cl

### ISSUE THREAD

**Issue by MattCarothers** [sn4k3/UVtools#202]
## System
 - OS: Windows 10

## Describe the bug
When I ran UVtools today, Windows Defender popped up an alert and then deleted some of the files.  I downloaded a fresh copy and attempted to install it, but Defender deleted it during install.  Looks like a false positive to me, but you can never be too careful.

## To Reproduce
1. Download the latest MSI release
2. Run the installer

## Expected behavior
UVtools installs

## Screenshots
![image](https://user-images.githubusercontent.com/4381389/118560326-4f82f980-b737-11eb-9ce8-2f44770aa04f.png)

**Comment by sn4k3** [comment]
Same as https://www.facebook.com/groups/uvtools/permalink/469791580797017/ ?

**Comment by derekantrican** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/5937

**Comment by MattCarothers** [comment]
Looks like the Avalonia devs resolved this with Microsoft.   I was able to install and run 2.13 just now with no issues.
