### ISSUE TITLE
[FEATURE REQUEST] Drain Hole in XYZ Accuracy Test

### ISSUE THREAD

**Issue by PrCRTL** [sn4k3/UVtools#205]
Hi, thanks for this great Tool.

I did the XYZ Accuracy Test today and missing a drainhole at the bottom... 
The print quality in this case a 40mm cube was according to that poor. 

best regards
Gerhard

**Comment by sn4k3** [comment]
What do you mean? You can activate the drain hole by check the option: **Relief with a center hole** and **Hollow model**

**Comment by PrCRTL** [comment]
A Drainhole goes through the Wall at the Bottom to let the inner resin pass through to avoid sucction.Tried all Options…Center hole makes a big hole in the base but it’s worthless if the part is direct on the Plate…Did I miss something? 

Gesendet von Yahoo Mail für iPhone


Am Montag, Mai 24, 2021, 11:41 schrieb Tiago Conceição ***@***.***>:




What do you mean? You can activate the drain hole by check the option: Relief with a center hole and Hollow model

**Comment by sn4k3** [comment]
The hole at bottom is just a relief hole and to drain in case of hollow, but i can't see what's the problem you having. Can you send some pictures of the result or of the problem?

**Comment by PrCRTL** [comment]
first picture showes how it comes generated with the relief hole and hollowed part... there is no way to drain anything as long the part sits on the plate...  You will see the bottom half of the print is not as it shoud be because of sucction....
on the second picture I made two examples in Black showing what I mean with a drain hole... as closest as possible to the plate to let the resin flow to remove sucction.... at least on one wall...
![Drain1](https://user-images.githubusercontent.com/7194561/119350274-6f6a6e00-bc9f-11eb-96dd-de3d9cb1a1a3.jpeg)
![Drain2](https://user-images.githubusercontent.com/7194561/119350284-72655e80-bc9f-11eb-87b1-cd11bc44b3dc.jpeg)

best regards
Gerhard

**Comment by sn4k3** [comment]
> there is no way to drain anything as long the part sits on the plate...

Not really... The print prints upside down so it's always draining, the top is open, which means when plate moves up the resin drops on vat and not stay inside the piece. The center hole is just a relief it will drain with our without it.

Do not confuse drain hole with vent hole. What you are refering to and show on picture is a vent hole which the function is let air pass to relief the pressure. I may implement this in future as a improvement to your request.

The bottom layers problem you have are due the elephant foot and prolongated exposure, which you can ignore for this test.

However your model indicate problems on your printer, either mechanical or level or settings, i have seen some cubes by now and the most i see are just perfect, no artifacts on surface like you are getting, suction never been a problem on this small models, the cube i printed myself come out perfect and aligned walls.
Also the lack of text engravings mean you maybe overexposing the part which can also lead to some problems here

**Comment by PrCRTL** [comment]
I see that you are using differnt terminology… in the Forums I’, in all are naming drain holes what you are calling Vent holes….

Don’t take me wrong, but you are simply wrong with your guess that its draining when the part is open… but this is not the right place to discuss that.

Finally I made my own cube with the holes and everything works as expected and looks perfect with the same settings… which are not perfect as you mentioned right… but that has its reason J

cheers

 

 

Von: Tiago Conceição ***@***.*** 
Gesendet: Montag, 24. Mai 2021 16:07
An: sn4k3/UVtools
Cc: Gerhard; Author
Betreff: Re: [sn4k3/UVtools] [FEATURE REQUEST] Drain Hole in XYZ Accuracy Test (#205)

 

there is no way to drain anything as long the part sits on the plate...

Not really... The print prints upside down so it's always draining, the top is open, which means when plate moves up the resin drops on vat and not stay inside the piece. The center hole is just a relief it will drain with our without it.

Do not confuse drain hole with vent hole. What you are refering to and show on picture is a vent hole which the function is let air pass to relief the pressure. I may implement this in future as a improvement to your request.

The bottom layers problem you have are due the elephant foot and prolongated exposure, which you can ignore for this test.

However your model indicate problems on your printer, either mechanical or level or settings, i have seen some cubes by now and the most i see are just perfect, no artifacts on surface like you are getting, suction never been a problem on this small models, the cube i printed myself come out perfect and aligned walls.
Also the lack of text engravings mean you maybe overexposing the part which can also lead to some problems here

**Comment by sn4k3** [comment]
Well i can be wrong, but to me the term drain seens more suited to remove something from inside, mostly a liquid. First entry on dictionary seens to agree with me, but i'm not an english native either so it can have other meanings that i'm not used to...
Glad that you able to fix yourself, i will add that feature in a future patch.

**Comment by sn4k3** [comment]
Closed by mistake, reopen until implemented

**Comment by sn4k3** [comment]
implemented
