### ISSUE TITLE
[BUG] Windows Defender blocking several files

### ISSUE THREAD

**Issue by Arakon** [sn4k3/UVtools#213]
As of today, Windows Defender detects and quarantines "Trojan:Win32/Emali.A!cl" in both Avalonia.Themes.Default.dll and Avalonia.Controls.DataGrid.dll. However, restoring them and even reinstalling UV Tools afterwards will make the app not launch at all anymore (no window, no error, nothing). Event viewer shows the following:

> > Application: UVtools.exe
> CoreCLR Version: 5.0.621.22011
> .NET Version: 5.0.6
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.BadImageFormatException: Could not load file or assembly 'Avalonia.Controls.DataGrid, Culture=neutral, PublicKeyToken=null'. Format of the executable (.exe) or library (.dll) is invalid.
> File name: 'Avalonia.Controls.DataGrid, Culture=neutral, PublicKeyToken=null'
>    at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
>    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
>    at System.Reflection.Assembly.Load(String assemblyString)
>    at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 243
>    at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 192
>    at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 203
>    at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri baseUri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 101
>    at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 50
>    at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
>    at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
>    at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 287
>    at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
>    at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 680
>    at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
>    at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
>    at UVtools.WPF.App.!XamlIlPopulate(IServiceProvider , App ) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\App.axaml:line 12
>    at UVtools.WPF.App.!XamlIlPopulateTrampoline(App )
>    at UVtools.WPF.App.Initialize() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\App.axaml.cs:line 40
>    at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
>    at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 147
>    at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 26
>

**Comment by sn4k3** [comment]
Also here:

https://github.com/sn4k3/UVtools/discussions/212
https://github.com/sn4k3/UVtools/issues/202

You will need to put UVtools folder in AV exclusions for now, and maybe temporary disable AV while installing.
Avalonia is trying to solve
