### ISSUE TITLE
[BUG] CXDLP file doesn't support by printer

### ISSUE THREAD

**Issue by dagov42** [sn4k3/UVtools#214]
## System
 - OS: [e.g. Windows 10 x64 v20H2]
 - Slicer: 
 - Printer: Creality CL-89 HALOT SKY

## Describe the bug
File have been converted from *.ctb to *.cxdlp. And it doesn't working.

## Screenshots
![2021-06-08 22-44-05](https://user-images.githubusercontent.com/62306927/121248467-283dc900-c8ac-11eb-9965-67988b15ff42.JPG)

**Comment by sn4k3** [comment]
Please attach both source and converted file.

**Comment by dagov42** [comment]
Ok,just in moment, it weight 700 Mb. I'll get the link.

**Comment by dagov42** [comment]
https://disk.yandex.ru/d/zZH1yZV34s7irA

**Comment by sn4k3** [comment]
Printer firmware has changed along with format, you should have the newest firmware.
This will require an update

**Comment by sn4k3** [comment]
Can you try print this file: https://we.tl/t-HmpKdXSS24
Do it without VAT first

**Comment by sn4k3** [comment]
Can you try print this file: https://we.tl/t-LfSOmMfFTv
Print it without VAT first

**Comment by dagov42** [comment]
![2021-06-09 07-55-04](https://user-images.githubusercontent.com/62306927/121296477-6e6d4980-c8f9-11eb-8658-7b631b2b529c.JPG)
I have the last one. And new file doesn't match.
![2021-06-09 08-04-32](https://user-images.githubusercontent.com/62306927/121296582-952b8000-c8f9-11eb-8416-c086d5d99f46.JPG)

**Comment by sn4k3** [comment]
Can you try this: https://we.tl/t-7mHg6BdzSW

**Comment by dagov42** [comment]
![IMG_20210611_001844](https://user-images.githubusercontent.com/62306927/121643746-d73ff780-ca9a-11eb-8f49-f076d4132f49.jpg)
It's so strange preview.

**Comment by sn4k3** [comment]
But does it prints?
Try this one to see if fixes the preview image: https://we.tl/t-z6wIqTLPw5

**Comment by dagov42** [comment]
Preview is not good, but prints good. I've attached converted file from ctb to cxdlp, original ctb and origianl cxdlp from creality box.

https://disk.yandex.ru/d/SOU3RGUFNhy5Eg
![2021-06-22 23-48-39](https://user-images.githubusercontent.com/62306927/123000580-6c56c080-d3b8-11eb-98bc-dde4c0762bc5.JPG)

**Comment by dagov42** [comment]
But problem - all parts mirrored

**Comment by sn4k3** [comment]
> But problem - all parts mirrored

The mirror is not generated by UVtools.
On your slicer you must check or uncheck the LCD Mirror to match your printer. Check on your slicer (chitubox i guess) the settings of the LCD, If is mirroed put normal. If is normal change to Mirror to fix this.

**Comment by dagov42** [comment]
No, I checked it on Chitubox. And preview ctb file on UVtools is right. But after converting it prints mirrored.

**Comment by sn4k3** [comment]
If is checked on chitubox you need to uncheck. Some printers don't require mirror and if you do it will print mirroed in wrong direction. Do that test.
