### ISSUE TITLE
[FEATURE REQUEST] Longer Orange 4k (.lgs4k) support

### ISSUE THREAD

**Issue by ycl413** [sn4k3/UVtools#218]
Can you please add support for the Longer Orange 4k (.lgs4k) file? I have attached the official chitubox plugin and a sample file.
[Longer3D-Orange4K-Windows64bit-V1.5.zip](https://github.com/sn4k3/UVtools/files/6644918/Longer3D-Orange4K-Windows64bit-V1.5.zip)
[LongerCoin_mono.zip](https://github.com/sn4k3/UVtools/files/6644921/LongerCoin_mono.zip)

**Comment by sn4k3** [comment]
I will take a look at it

**Comment by sn4k3** [comment]
Implemented
