### ISSUE TITLE
[BUG] Wrong icon for "Repair layers and issues"

### ISSUE THREAD

**Issue by FutureJames** [sn4k3/UVtools#227]
## Describe the bug
The icon used in the "Tools" menu for "Repair Layers and Issues" does not match the button with the same function in the "Issues" tab on the left side of the window.  There is a toolbox used in the "Tools" menu and a wrench used in the "Issues" tab.  These are the same function and should use the same button.  The wrench icon is used in the "Tools" menu for a completely different function ("Edit Print Parameters") 

## To Reproduce
1. Go to "Tools" menu
2. Read down to "Repair Layers and Issues"
4. See tool box icon
5. close menu
6. click on "Issues" tab
7. look at icon for "Repair Layers and Issues"
8. observe that it is a wrench 

## Screenshots

![BUG 2021-06-21_23-37](https://user-images.githubusercontent.com/6488279/122876044-e3715380-d2e9-11eb-8db7-6dffc24d88dd.png)
![BUG 2021-06-21_23-38](https://user-images.githubusercontent.com/6488279/122876046-e409ea00-d2e9-11eb-9a43-a64e66f546d6.png)
![BUG 2021-06-21_23-36](https://user-images.githubusercontent.com/6488279/122876047-e409ea00-d2e9-11eb-83dd-82d39bab6684.png)

## Additional context
The tool is not broken, the icons are just not being used consistently.  I assume that this is not intentional.

**Comment by sn4k3** [comment]
Yeah, will update accordingly

**Comment by FutureJames** [comment]
On that same topic, the icon for "Outline" and "Morph" are the same and also confusing.  (although they both have text labels, so less of an issue).  See attached screenshot
![BUG 2021-06-22_23-37](https://user-images.githubusercontent.com/6488279/123048132-eab06400-d3b2-11eb-9261-a995d2f93274.png)

**Comment by sn4k3** [comment]
Maybe i should change the **Outine** to **View**? Can't find a proper icon.
You can advice one or from: https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free

**Comment by FutureJames** [comment]
I think "outline" makes a lot of sense as a label.  Perhaps one of these icons would be a good alternative:
https://fontawesome.com/v5.15/icons/vector-square?style=solid
https://fontawesome.com/v5.15/icons/square?style=regular

Also, maybe a fun one for "Elephant Foot" :)
https://fontawesome.com/v5.15/icons/republican?style=solid

**Comment by sn4k3** [comment]
The normal square also look like an checkbox...
The vector is better but still not perfect.

The elephant foot icon is actually a elephant foot, but at it size don't seen like it

**Comment by FutureJames** [comment]
Yeah that is a good point.  It does kind of look like a checkbox.
This one is probably closest to the concept of outlining an area:
https://fontawesome.com/v5.15/icons/draw-polygon?style=solid

This one also gives a bit of the feeling of outline multiple areas:
https://fontawesome.com/v5.15/icons/border-all?style=solid

**Comment by sn4k3** [comment]
I think i will go with the square vector. Can always change latter ;)
