### ISSUE TITLE
Decode UVJ file: the case when JSON settings/config has an empty `Layers` array

### ISSUE THREAD

**Issue by Megidd** [sn4k3/UVtools#232]
### Discussed in https://github.com/sn4k3/UVtools/discussions/231

<div type='discussions-op-text'>

<sup>Originally posted by **Megidd** July  3, 2021</sup>
Sometimes I'm observing this exception, could it be a bug? The exception is observed *occasionally* 😕 

The troublemaker file is attached too.

[128034414.zip](https://github.com/sn4k3/UVtools/files/6758101/128034414.zip)

![image](https://user-images.githubusercontent.com/17475482/124348431-20e5b300-dbff-11eb-892a-f75ad84cc434.png)
</div>

**Comment by Megidd** [comment]
Also, this exception is thrown when `Layers` array is `null` rather than *empty*. So, maybe two checks might be needed:

1. Array is *not* empty
2. Array is *not* null

![2021-07-03 16_38_49-Window](https://user-images.githubusercontent.com/17475482/124353746-86489c80-dc1d-11eb-985b-b27d3caf3885.png)

**Comment by sn4k3** [comment]
> Also, this exception is thrown when `Layers` array is `null` rather than _empty_. So, maybe two checks might be needed:
> 
> 1. Array is _not_ empty
> 2. Array is _not_ null

Ok just need to put a **?** after layers: `JsonSettings.Layers?.Count`

**Comment by sn4k3** [comment]
Fixed
