### ISSUE TITLE
[BUG]  Resize feature "increase towards 100%" is wrong

### ISSUE THREAD

**Issue by Liger0** [sn4k3/UVtools#235]
## System
 - OS: Windows 10 x64 v21H1
 - Slicer: Lychee
 - Printer: Photon mono se

## Describe the bug
The option "increase towards 100%" doesn't consider the input value (95%), and it starts instead as 0%, so that the first layer is empty and then it goes gradually from 0 to 100% regardless of the value specified

## To Reproduce
1. Go to "Resize"
2. Click on "Range layer selector", select "bottom layers"
3. Select a value of around 95% for Resize
4. Tick "increase or decrease towards 100%"
5. Click resize

## Expected behavior
Take the input value into consideration and start from that.

**Comment by sn4k3** [comment]
Fixed
