### ISSUE TITLE
[BUG] Elfin (Number of Slices = x)" to ";Number of Slices = x"

### ISSUE THREAD

**Issue by checksummaster** [sn4k3/UVtools#24]
I own an elfin printer and I use uvtools to convert sl1 to cws format. To make it work, I need to change in the gcode in the cws ";(Number of Slices         = 2405)" to ";Number of Slices         = 2405" ( remove () )

without it, the printed said  "No 'Number of Slices' line in gcode file"

Thanks by the way for this super tool :)

Note: now I presently printing ... will give feedback if something else wrong

**Comment by sn4k3** [comment]
Thank you for spoting this, will fix on next release

**Comment by sn4k3** [comment]
fixed
