### ISSUE TITLE
[BUG] Creality Halot-One new firmware not compatible with v2.14.3

### ISSUE THREAD

**Issue by Calvir** [sn4k3/UVtools#240]
## System
 - OS: Windows 10 x64 v20H2
 - Slicer: chitubox
 - Printer: Halot-one

## Describe the bug
the converted file to cxdlp which was working before, don't work anymore. I did a firmware update of my printer yesterday, and all the files I converted with UVtools don't worked now. I think creality modified is file format.
[test slice.zip](https://github.com/sn4k3/UVtools/files/6813865/test.slice.zip)

## To Reproduce
1. slice a file with chitubox in cbddlp file format
2. convert in cxdlp with UVtools

## Files

 Thank you for you work and updates

**Comment by sn4k3** [comment]
Posting header differenteces.
original left, uvtools right:

![image](https://user-images.githubusercontent.com/113281/125656984-eec44855-e90f-4022-b056-ae3fa6f7b526.png)
![image](https://user-images.githubusercontent.com/113281/125656997-e00d59e4-4226-4092-986e-32a3e1a77396.png)

**Comment by sn4k3** [comment]
fixed

**Comment by Calvir** [comment]
after test, it work fine.
Thank you
