### ISSUE TITLE
[FEATURE REQUEST]  New GUI

### ISSUE THREAD

**Issue by swtrse** [sn4k3/UVtools#242]
I found this in an older issue
> # is getting very strong and well built language with lot of eases today, very capable, the only downside with UVtools was i start with WinForm (Windows stuck), i never planed to build UVtools to this advanced stage, but someday i plan to convert it to Avalonia WPF which is cross platform GUI, the UVtools.Core and Cmd is already cross platform and ready to put on every OS.

I just want to mention at the current point It would be an option to wait a bit longer and then use Project MAUI for GUI.
MAUI is the successor to Xamarin and it's goal is to support GUI for all Systems running .net6. Release is planed late 2021 and it is developed and maintained by Microsoft and of course open source too.
https://github.com/dotnet/maui

**Comment by sn4k3** [comment]
Where do you find that text?
UVtools is already cross platform, using Avalonia. So the text is no longer true.
