### ISSUE TITLE
[BUG] UVtools is 64-bit but installs to Program Files (x86)/ folder under Windows

### ISSUE THREAD

**Issue by jtcmedia** [sn4k3/UVtools#254]
## System
 - OS: Windows 10 x64 v21H1

## Describe the bug
By default, this is installing to Program Files (x86)/ folder. This should install to the Program Files/ folder if it is 64 bit.

## To Reproduce
Install using defaults

## Expected behavior
Should install to Program Files/ not Program Files (x86)/

**Comment by sn4k3** [comment]
Thats because registering program as x64 on WIX is a pain. but i will look again into it

**Comment by sn4k3** [comment]
Fixed

**Comment by jtcmedia** [comment]
@sn4k3 super! thanks!
