### ISSUE TITLE
[BUG] Calibration ctb files with generated thumbnails can't open with Chitubox

### ISSUE THREAD

**Issue by human890209** [sn4k3/UVtools#263]
I tried to use Chitubox 1.9.0 to view the 3D result of ctb files from UVTools 2.18.0.
Most ctb files work. But the calibration files with a newly generated thumbnail image are invalid.
I replaced the thumbnail images and use a self-made script to set ctbSlicerFile.RequireFullEncode = true to encode the thumbnail.
Save it as a new ctb file.
This ctb could open with Chitubox!

(Bug Report: The thumbnail images are not saved in ctb file if that is not a full save.)

**Comment by sn4k3** [comment]
Provide the problematic file

**Comment by human890209** [comment]
I search "cbt" In this repository and got several results. Should they be replaced with "ctb"?

**Comment by sn4k3** [comment]
> I search "cbt" In this repository and got several results. Should they be replaced with "ctb"?

Yes, CTB comes from **C**hi**T**u**B**ox

**Comment by human890209** [comment]
After Exposure Time Finder or another calibration tool is generated, the thumbnail view window of UVTools is not updated automatically.
I could click the page left or page right button to update the thumbnail view manually, but I think it should update automatically if the thumbnail is replaced.

**Comment by human890209** [comment]
And also a tool that could draw on the thumbnail image like the pixel editor (Draw, Text, Erase) is welcomed!

**Comment by sn4k3** [comment]
> After Exposure Time Finder or another calibration tool is generated, the thumbnail view window of UVTools is not updated automatically.
> I could click the page left or page right button to update the thumbnail view manually, but I think it should update automatically if the thumbnail is replaced by the script.

I know a bout that. 
The Core can't access UI.
Not a big deal...

> And also a tool that could draw on the thumbnail image like the pixel editor (Draw, Text, Erase) is welcomed!
> Thumbnail Editor. Same UI (without Support and Hole) will do. Layer0 is Image1/2. Image2/2 could be generated from Image1/2.

That's a waste of time.
You can still upload and replace thumbnails by a image on  your disk

**Comment by human890209** [comment]
How did the Properties and Layer Data UI update the values? By a fixed updated time?

**Comment by sn4k3** [comment]
> How did the Properties and Layer Data UI update the values? By a fixed update interval?

Direct bound properties are via notify.
Layer data is updated every layer change
An other indirect bounds are via a forced full refresh of the UI

**Comment by human890209** [comment]
I tried this code in my script:
`
            // Update the thumbnails
            Mat myThumbnail = SlicerFile.GetThumbnail().Clone();
            SlicerFile.SetThumbnails(myThumbnail);
`
The save-as ctb file can't open with Chitubox.

**Comment by sn4k3** [comment]
Current version have a bug with v4. You need to wait for the patch

**Comment by human890209** [comment]
`
Mat[] myThumbnail = new Mat[2];
myThumbnail[0] = SlicerFile.GetThumbnail(300).Clone();
myThumbnail[1] = SlicerFile.GetThumbnail(125).Clone();
SlicerFile.SetThumbnails(myThumbnail);
`
I tried these codes, the ctb file can be opened with Chitubox.
I guess CvInvoke.Resize(Thumbnails[i], Thumbnails[i], ThumbnailsOriginalSize[i]) corrupt something.

**Comment by sn4k3** [comment]
Fixed
