### ISSUE TITLE
[BUG] Incorrect calculation MaterialMilliliters after "Dynamic Layer Height"

### ISSUE THREAD

**Issue by Sat360** [sn4k3/UVtools#273]
## System
 - OS: [e.g. Windows 10 x64 v20H2]
 - Slicer: 
 - Printer: 

## Describe the bug
When I change layer height by "Dynamic layer height" material milliliters in "Layer data" area become incorrect. And "Volume" in "I printed this file" window becomes incorrect too.

## To Reproduce
1. Open attached file (just cube 10x10x10mm, layer height 0.02mm). [Cube_10_10_10.zip](https://github.com/sn4k3/UVtools/files/7063863/Cube_10_10_10.zip)
2. Apply "Tools - Dynamic layer height" with parameters: MinimumLayerHeight = 0.020, MaximumLayerHeight = 0.100". Layers counts will be decreased by 5 times.
3. Go to last layer. Look at "Layer data". MaterialMilliliters is 0.8014ml. Correct value is about 0.01ml.

## Expected behavior

Each layer must be 0.01ml. File - I was printed this file window must show 1ml.

## Screenshots

![1](https://user-images.githubusercontent.com/816787/131065718-d6ed56b0-6c05-4b28-9f95-412a9a39a10a.png)
 
## Additional context

First layer calculating correct, 0.01ml. But each next layer by 80% bigger than previous.

**Comment by sn4k3** [comment]
Fixed
