### ISSUE TITLE
[BUG] Incorrect "Normal exposure" at Dynamic Layer Height dialog

### ISSUE THREAD

**Issue by Sat360** [sn4k3/UVtools#274]
## System
 - OS: [e.g. Windows 10 x64 v20H2]
 - Slicer: 
 - Printer: 

## Describe the bug
When I choose "Exposure set type = Multiplier" at Dynamic Layer Height dialog, I got same start values for bottom exposure time and normal exposure time.

## Screenshots

![изображение](https://user-images.githubusercontent.com/816787/131095194-7fe0a2bf-8976-47cc-ae41-1dd74226e50c.png)

## Additional context

Error in "OperationDynamicLayerHeight.cs" file, line 348.
Now:
exposure = (decimal)SlicerFile.BottomExposureTime + (decimal)SlicerFile.ExposureTime * count * layerHeight * _exposureStep;
Must be:
exposure = (decimal)SlicerFile.ExposureTime + (decimal)SlicerFile.ExposureTime * count * layerHeight * _exposureStep;

I'm sorry, I don't know how to use github :)

**Comment by sn4k3** [comment]
Fixed
