### ISSUE TITLE
[FEATURE REQUEST] Add checkbox "Merge only equivalent layers" in Dynamic Layer Height.

### ISSUE THREAD

**Issue by Sat360** [sn4k3/UVtools#275]
## Is your feature request related to a problem? Please describe
Current Dynamic Layer Height algorythm too strong.

## Describe the solution you'd like
I will now try to print a test file. Already now I see that the algorithm "eats up" small details very strongly. He simply does not see a line with a height of 0.1 mm. This is a noticeable detail. And the tilt angle is quite large - 78 degrees (0.1mm width and 0.02mm height).
I looked in the source code. As I understand it, the program takes the difference between the two layers (at my screenshot, a line 2 pixels wide is obtained) and narrows the picture by 1 pixel. 2 pixels minus 1 pixel on each side - it turns out that the strip has disappeared :)
Is it possible to somehow change the algorithm so that it only reduce 1 pixel of difference?
And in any case, please add the checkbox "Merge layers only if they are completely the same". This will be useful for "geometrically" details.

## Screenshots
![изображение](https://user-images.githubusercontent.com/816787/131100182-67435428-4d45-46ab-85ea-7dae17b306f6.png)

**Comment by sn4k3** [comment]
Implemented
