### ISSUE TITLE
[BUG] All layers same exposure time (bottom exposure time) for .pwmo (Anycubic Moni)

### ISSUE THREAD

**Issue by th-m-vogel** [sn4k3/UVtools#278]
## System
 - OS: Windows 10 x64
 - UVtools Version: 2.20.3 X64
 - Slicer: Photon Workshop 
 - Printer: Anycubic Photon Mono

## Describe the bug
Any slices are exposed the same time, what is in this case the bottom layer exposure time.

## To Reproduce
1. Slice a object (Photon Workshop or Chitubox)
2. import in UVtools
3. Save
4. print the file saved from UVtools, everything is hard overexposed
5. extract file contes with UVtools
6. check layers.ini

## Expected behavior
non bottom layer are exposed by standard exposure time

## sample data from configuration.ini
[Header]
Section = [Mark: HEADER, Length: 80]
PixelSizeUm = 51
LayerHeight = 0.05
LayerExposureTime = 3.2
LightOffDelay = 0.4
BottomExposureSeconds = 20
BottomLayersCount = 4
LiftHeight = 8
LiftSpeed = 3
RetractSpeed = 6
VolumeMl = 3905.846
AntiAliasing = 1
ResolutionX = 1620
ResolutionY = 2560
WeightG = 0
Price = 0.25521803
PriceCurrencyDec = 36
PriceCurrencySymbol = $
PerLayerOverride = 0
PrintTime = 37980
Padding1 = 0
Padding2 = 0

## sample data from layers.ini, layer 10 what is not a bulttom layer
[10]
NonZeroPixelCount: 233335
BoundingRectangle: {X=528,Y=626,Width=564,Height=985}
IsBottomLayer: False
LayerHeight: 0.05
PositionZ: 0.55
ExposureTime: 20
LiftHeight: 8
LiftSpeed: 180
MaterialMilliliters: 0.0303ml (0.00%)

**Comment by sn4k3** [comment]
I tried to replicate this, but it works for me.
Can you send me your file both before and after save with uvtools?
Here my output:

```
[FileMark]
Mark = ANYCUBIC
Version = 1
AreaNum = 4
HeaderAddress = 48
Padding1 = 0
PreviewAddress = 144
PreviewEndAddress = 75436
LayerDefinitionAddress = 75436
Padding2 = 0
LayerImageAddress = 84416

[Header]
Section = [Mark: HEADER, Length: 80]
PixelSizeUm = 50
LayerHeight = 0.025
LayerExposureTime = 1
LightOffDelay = 12.53
BottomExposureSeconds = 10
BottomLayersCount = 3
LiftHeight = 7
LiftSpeed = 1.33
RetractSpeed = 1.33
VolumeMl = 752.518
AntiAliasing = 1
ResolutionX = 3840
ResolutionY = 2400
WeightG = 0
Price = 0
PriceCurrencyDec = 36
PriceCurrencySymbol = $
PerLayerOverride = 1
PrintTime = 7623
Padding1 = 0
Padding2 = 0

[0]
NonZeroPixelCount: 354596
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: True
LayerHeight: 0.025
PositionZ: 0.025
ExposureTime: 10
LiftHeight: 15
LiftSpeed: 19.8
MaterialMilliliters: 0.0222ml (0.00%)

[1]
NonZeroPixelCount: 354806
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: True
LayerHeight: 0.025
PositionZ: 0.05
ExposureTime: 10
LiftHeight: 15
LiftSpeed: 19.8
MaterialMilliliters: 0.0222ml (0.00%)

[2]
NonZeroPixelCount: 354633
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: True
LayerHeight: 0.025
PositionZ: 0.075
ExposureTime: 10
LiftHeight: 15
LiftSpeed: 19.8
MaterialMilliliters: 0.0443ml (0.01%)

[3]
NonZeroPixelCount: 354657
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: False
LayerHeight: 0.025
PositionZ: 0.1
ExposureTime: 1
LiftHeight: 7
LiftSpeed: 79.8
MaterialMilliliters: 0.0665ml (0.01%)

[4]
NonZeroPixelCount: 354835
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: False
LayerHeight: 0.025
PositionZ: 0.125
ExposureTime: 1
LiftHeight: 7
LiftSpeed: 79.8
MaterialMilliliters: 0.0222ml (0.00%)

[5]
NonZeroPixelCount: 354996
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: False
LayerHeight: 0.025
PositionZ: 0.15
ExposureTime: 1
LiftHeight: 7
LiftSpeed: 79.8
MaterialMilliliters: 0.1109ml (0.01%)

[6]
NonZeroPixelCount: 355153
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: False
LayerHeight: 0.025
PositionZ: 0.175
ExposureTime: 1
LiftHeight: 7
LiftSpeed: 79.8
MaterialMilliliters: 0.1332ml (0.02%)

[7]
NonZeroPixelCount: 355306
BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}
IsBottomLayer: False
LayerHeight: 0.025
PositionZ: 0.2
ExposureTime: 1
LiftHeight: 7
LiftSpeed: 79.8
MaterialMilliliters: 0.1554ml (0.02%)
```

**Comment by th-m-vogel** [comment]
Original mail, Message size exceeded error … following up with multiple mail, single file attached.


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Thomas ***@***.***>
Gesendet: Sonntag, 29. August 2021 16:46
An: ***@***.***>
Betreff: AW: [sn4k3/UVtools] [BUG] All layers same exposure time (bottom exposure time) for .pwmo (Anycubic Moni) (#278)

Hi,

thanks for fast Response. I realized something is wrong when printing some of the included calibration tests, i.e. Elefant foot calibration.

Slicing with Photon Workshop and direct going to print, I never had a Problem.
Attached a pwmo sliced with Photon Workshop and the same after Opening and saving as with UVtools.

Also, the extracted ini data from UVtools.

I also attached a ElefanfFoot test generated in UVtools same issue, all layers at 20 seconds

One Question, how to extract the data from a pwmo file without the use of UVtools?

Best Regards, Thomas

Screenshot UVtools, elefant foot, layer 34, IsBottomLayer: False, ExposureTime: 20s
***@***.***

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Tiago ***@***.***>
Gesendet: Sonntag, 29. August 2021 15:50
An: ***@***.***>
Cc: Thomas M. ***@***.***>; ***@***.***>
Betreff: Re: [sn4k3/UVtools] [BUG] All layers same exposure time (bottom exposure time) for .pwmo (Anycubic Moni) (#278)


I tried to replicate this, but it works for me.
Can you send me your file both before and after save with uvtools?
Here my output:

[FileMark]

Mark = ANYCUBIC

Version = 1

AreaNum = 4

HeaderAddress = 48

Padding1 = 0

PreviewAddress = 144

PreviewEndAddress = 75436

LayerDefinitionAddress = 75436

Padding2 = 0

LayerImageAddress = 84416



[Header]

Section = [Mark: HEADER, Length: 80]

PixelSizeUm = 50

LayerHeight = 0.025

LayerExposureTime = 1

LightOffDelay = 12.53

BottomExposureSeconds = 10

BottomLayersCount = 3

LiftHeight = 7

LiftSpeed = 1.33

RetractSpeed = 1.33

VolumeMl = 752.518

AntiAliasing = 1

ResolutionX = 3840

ResolutionY = 2400

WeightG = 0

Price = 0

PriceCurrencyDec = 36

PriceCurrencySymbol = $

PerLayerOverride = 1

PrintTime = 7623

Padding1 = 0

Padding2 = 0



[0]

NonZeroPixelCount: 354596

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.025

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0222ml (0.00%)



[1]

NonZeroPixelCount: 354806

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.05

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0222ml (0.00%)



[2]

NonZeroPixelCount: 354633

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.075

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0443ml (0.01%)



[3]

NonZeroPixelCount: 354657

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.1

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.0665ml (0.01%)



[4]

NonZeroPixelCount: 354835

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.125

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.0222ml (0.00%)



[5]

NonZeroPixelCount: 354996

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.15

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1109ml (0.01%)



[6]

NonZeroPixelCount: 355153

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.175

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1332ml (0.02%)



[7]

NonZeroPixelCount: 355306

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.2

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1554ml (0.02%)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsn4k3%2FUVtools%2Fissues%2F278%23issuecomment-907794825&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183530044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CLVlByw595qybKo6WyeM5Zx%2FjeOB80FYIX%2Fv984%2B%2FUM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABD7SSHMTCNNTFXXCTNJHRDT7I3JRANCNFSM5DAH4TAQ&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183530044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SKSdKRjLUf9rya9hrULekDfmvaXKTrQ54Uhwwq5VHAU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183540033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YNMtqVfm630C%2BAU%2FmtLlQG2AjbSUXGryMAhj%2BjSCTds%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183540033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9Tegml3KN4BlpDluxluN7zh%2F5slNHuje9cduajBHBug%3D&reserved=0>.

**Comment by th-m-vogel** [comment]
Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Thomas ***@***.***>
Gesendet: Sonntag, 29. August 2021 16:46
An: ***@***.***>
Betreff: AW: [sn4k3/UVtools] [BUG] All layers same exposure time (bottom exposure time) for .pwmo (Anycubic Moni) (#278)

Hi,

thanks for fast Response. I realized something is wrong when printing some of the included calibration tests, i.e. Elefant foot calibration.

Slicing with Photon Workshop and direct going to print, I never had a Problem.
Attached a pwmo sliced with Photon Workshop and the same after Opening and saving as with UVtools.

Also, the extracted ini data from UVtools.

I also attached a ElefanfFoot test generated in UVtools same issue, all layers at 20 seconds

One Question, how to extract the data from a pwmo file without the use of UVtools?

Best Regards, Thomas

Screenshot UVtools, elefant foot, layer 34, IsBottomLayer: False, ExposureTime: 20s
***@***.***

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Tiago ***@***.***>
Gesendet: Sonntag, 29. August 2021 15:50
An: ***@***.***>
Cc: Thomas M. ***@***.***>; ***@***.***>
Betreff: Re: [sn4k3/UVtools] [BUG] All layers same exposure time (bottom exposure time) for .pwmo (Anycubic Moni) (#278)


I tried to replicate this, but it works for me.
Can you send me your file both before and after save with uvtools?
Here my output:

[FileMark]

Mark = ANYCUBIC

Version = 1

AreaNum = 4

HeaderAddress = 48

Padding1 = 0

PreviewAddress = 144

PreviewEndAddress = 75436

LayerDefinitionAddress = 75436

Padding2 = 0

LayerImageAddress = 84416



[Header]

Section = [Mark: HEADER, Length: 80]

PixelSizeUm = 50

LayerHeight = 0.025

LayerExposureTime = 1

LightOffDelay = 12.53

BottomExposureSeconds = 10

BottomLayersCount = 3

LiftHeight = 7

LiftSpeed = 1.33

RetractSpeed = 1.33

VolumeMl = 752.518

AntiAliasing = 1

ResolutionX = 3840

ResolutionY = 2400

WeightG = 0

Price = 0

PriceCurrencyDec = 36

PriceCurrencySymbol = $

PerLayerOverride = 1

PrintTime = 7623

Padding1 = 0

Padding2 = 0



[0]

NonZeroPixelCount: 354596

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.025

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0222ml (0.00%)



[1]

NonZeroPixelCount: 354806

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.05

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0222ml (0.00%)



[2]

NonZeroPixelCount: 354633

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.075

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0443ml (0.01%)



[3]

NonZeroPixelCount: 354657

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.1

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.0665ml (0.01%)



[4]

NonZeroPixelCount: 354835

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.125

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.0222ml (0.00%)



[5]

NonZeroPixelCount: 354996

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.15

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1109ml (0.01%)



[6]

NonZeroPixelCount: 355153

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.175

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1332ml (0.02%)



[7]

NonZeroPixelCount: 355306

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.2

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1554ml (0.02%)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsn4k3%2FUVtools%2Fissues%2F278%23issuecomment-907794825&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183530044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CLVlByw595qybKo6WyeM5Zx%2FjeOB80FYIX%2Fv984%2B%2FUM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABD7SSHMTCNNTFXXCTNJHRDT7I3JRANCNFSM5DAH4TAQ&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183530044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SKSdKRjLUf9rya9hrULekDfmvaXKTrQ54Uhwwq5VHAU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183540033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YNMtqVfm630C%2BAU%2FmtLlQG2AjbSUXGryMAhj%2BjSCTds%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183540033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9Tegml3KN4BlpDluxluN7zh%2F5slNHuje9cduajBHBug%3D&reserved=0>.

**Comment by th-m-vogel** [comment]
Hi,

additional info, UVtools opens with the UVtools_demo_file. Converting this to Photon Mono (pwmo) does not produce this bug!

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Tiago ***@***.***>
Gesendet: Sonntag, 29. August 2021 15:50
An: ***@***.***>
Cc: Thomas M. ***@***.***>; ***@***.***>
Betreff: Re: [sn4k3/UVtools] [BUG] All layers same exposure time (bottom exposure time) for .pwmo (Anycubic Moni) (#278)


I tried to replicate this, but it works for me.
Can you send me your file both before and after save with uvtools?
Here my output:

[FileMark]

Mark = ANYCUBIC

Version = 1

AreaNum = 4

HeaderAddress = 48

Padding1 = 0

PreviewAddress = 144

PreviewEndAddress = 75436

LayerDefinitionAddress = 75436

Padding2 = 0

LayerImageAddress = 84416



[Header]

Section = [Mark: HEADER, Length: 80]

PixelSizeUm = 50

LayerHeight = 0.025

LayerExposureTime = 1

LightOffDelay = 12.53

BottomExposureSeconds = 10

BottomLayersCount = 3

LiftHeight = 7

LiftSpeed = 1.33

RetractSpeed = 1.33

VolumeMl = 752.518

AntiAliasing = 1

ResolutionX = 3840

ResolutionY = 2400

WeightG = 0

Price = 0

PriceCurrencyDec = 36

PriceCurrencySymbol = $

PerLayerOverride = 1

PrintTime = 7623

Padding1 = 0

Padding2 = 0



[0]

NonZeroPixelCount: 354596

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.025

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0222ml (0.00%)



[1]

NonZeroPixelCount: 354806

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.05

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0222ml (0.00%)



[2]

NonZeroPixelCount: 354633

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: True

LayerHeight: 0.025

PositionZ: 0.075

ExposureTime: 10

LiftHeight: 15

LiftSpeed: 19.8

MaterialMilliliters: 0.0443ml (0.01%)



[3]

NonZeroPixelCount: 354657

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.1

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.0665ml (0.01%)



[4]

NonZeroPixelCount: 354835

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.125

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.0222ml (0.00%)



[5]

NonZeroPixelCount: 354996

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.15

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1109ml (0.01%)



[6]

NonZeroPixelCount: 355153

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.175

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1332ml (0.02%)



[7]

NonZeroPixelCount: 355306

BoundingRectangle: {X=1393,Y=749,Width=1054,Height=902}

IsBottomLayer: False

LayerHeight: 0.025

PositionZ: 0.2

ExposureTime: 1

LiftHeight: 7

LiftSpeed: 79.8

MaterialMilliliters: 0.1554ml (0.02%)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsn4k3%2FUVtools%2Fissues%2F278%23issuecomment-907794825&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183530044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CLVlByw595qybKo6WyeM5Zx%2FjeOB80FYIX%2Fv984%2B%2FUM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABD7SSHMTCNNTFXXCTNJHRDT7I3JRANCNFSM5DAH4TAQ&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183530044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SKSdKRjLUf9rya9hrULekDfmvaXKTrQ54Uhwwq5VHAU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183540033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YNMtqVfm630C%2BAU%2FmtLlQG2AjbSUXGryMAhj%2BjSCTds%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ced184362830a47ab22a908d96af3ef37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658418183540033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9Tegml3KN4BlpDluxluN7zh%2F5slNHuje9cduajBHBug%3D&reserved=0>.

**Comment by sn4k3** [comment]
I found the bug, it's general, it happen on all files on calibration tests

**Comment by th-m-vogel** [comment]
Hi,

Update, It happens only to pwmo files sliced using Photon Workshop. Scliced using chitubox or Lychee it does not happen. Attached a Photon Workshop slice

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Tiago ***@***.***>
Gesendet: Sonntag, 29. August 2021 17:24
An: ***@***.***>
Cc: Thomas M. ***@***.***>; ***@***.***>
Betreff: Re: [sn4k3/UVtools] [BUG] All layers same exposure time (bottom exposure time) for .pwmo (Anycubic Moni) (#278)


I found the bug, it's general, it happen on all files on calibration tests

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsn4k3%2FUVtools%2Fissues%2F278%23issuecomment-907810763&data=04%7C01%7C%7Cab3f6ec259064108f1bd08d96b010ca3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658474515259185%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Uh4c%2F%2BhDD7JEDUfD4lz8qT3dRik7H6zR7XVMh3U16Yw%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABD7SSAAYXJQVD3REVKTWTTT7JGJTANCNFSM5DAH4TAQ&data=04%7C01%7C%7Cab3f6ec259064108f1bd08d96b010ca3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658474515269173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5AJSavmxrUcpct5EnTWOujj3UlOApylIslm9M4ljqVA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cab3f6ec259064108f1bd08d96b010ca3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658474515269173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y0M5qhdtzVFzYCpWvj3pzdGk4bDMpGlZJJDAfi5ogvQ%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cab3f6ec259064108f1bd08d96b010ca3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637658474515279169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=isawn8Q3G7H8JsphZmTxJyW%2BhXJR4ZNA2%2B%2FJnxBJKM0%3D&reserved=0>.

**Comment by sn4k3** [comment]
Fixed on new release
