### ISSUE TITLE
[BUG] Resin trap issue detection

### ISSUE THREAD

**Issue by jimokeane** [sn4k3/UVtools#285]
Latest version seems to get stuck computing issues on the resin trap detection step. It just bounces up / down over the same layers and never finishes.

## System
 - OS: MacOS 10.15.7
 - Slicer: Lychee
 - Printer: Anycubic Photon (.photon file)

## Describe the bug
Latest version seems to get stuck computing issues on the resin trap detection step. It just bounces up / down over the same layers and never finishes.

## To Reproduce
1. Load Lychee sliced .photon file

## Expected behavior
Not going into infinite loop

**Comment by sn4k3** [comment]
Most probable is your file is complex with to much holes.

See:

1. https://github.com/sn4k3/UVtools/issues/268
2. https://github.com/sn4k3/UVtools/issues/221

Attach your file if you want futher investigation

**Comment by sn4k3** [comment]
New release give more performance.
