### ISSUE TITLE
[BUG] Error converting any file to Chitubox CTBv4 on MacOS

### ISSUE THREAD

**Issue by madeinoz67** [sn4k3/UVtools#286]
## System
 - OS: macos 11.5.2
 - Slicer: Lychee
 - Printer: Photon S
 - UVTools: v2.21.1

## Describe the bug
When trying to convert any file to ctbv4 I receive an error "The save file operation failed" (screenshot attached)

When converting to other formats all is as expected

## To Reproduce
1. Click on File menu 
2. Click on convert to...
3. Scroll down to 'convert to Chitubox V4 format'
4. delay is seen then error dialog appears

## Expected behavior
file dialog should open and save to new format.

## Screenshots

![2021-09-09_16-46-36](https://user-images.githubusercontent.com/4160293/132654596-ddfdd5df-aad7-418d-942c-c525c9d8e719.png)

**Comment by sn4k3** [comment]
That error is not from UVtools. Something on mac is not allowing to do the operation.
Try to convert to .rgb.cws does same message shows?

**Comment by madeinoz67** [comment]
thanks for that, yes same error as above for "Creation Workshop X" .xml.cws  so will track things down locally.

**Comment by sn4k3** [comment]
ok so mac is triping when i have two extensions on filters. But i tested on my VM and it works. BigSur X64.

**Comment by sn4k3** [comment]
Fixed
