### ISSUE TITLE
trojan horse in build

### ISSUE THREAD

**Issue by nostone123** [sn4k3/UVtools#306]
hi there downloaded the latest release UVtools_win-x64_v2.23.1.zip and it contains a trojan horse (TR/YAV.MINERVA.NBREQ) in the cvextern.dll file

**Comment by tslater2006** [comment]
There is no trojan horse. It is a false positive by your anti-virus and that file is part of the OpenCV image processing library.

**Comment by sn4k3** [comment]
https://github.com/sn4k3/UVtools/discussions/298
