### ISSUE TITLE
[FEATURE REQUEST] - Add LGS30 (Longer Orange 30) Support

### ISSUE THREAD

**Issue by calipzo** [sn4k3/UVtools#34]
**Is your feature request related to a problem? Please describe.**
Please, add support for Longer Orange 30. http://www.longer3d.com/desktop-3d-printers/orange-30.html

**Comment by sn4k3** [comment]
It does support .zip file as website says or only .lgs files?

**Comment by calipzo** [comment]
It supports only .lgs* file format. [Here is](https://drive.google.com/drive/u/0/folders/14xkjh8ANF017PYC-0Ux6hcRnbPPbAesO?fbclid=IwAR2XyvSs_jCWwqXymOh9ZEvcuyKNuj-ibnmbLAmfOsZMWzjJdke71kxANwQ) official plugin for ChituBox.

**Comment by sn4k3** [comment]
Implemented
