### ISSUE TITLE
[FEATURE REQUEST] Add "Send to External Application" to save menu.

### ISSUE THREAD

**Issue by ccatlett1984** [sn4k3/UVtools#352]
My example would be Lychee slicer, which after slicing offers me the option to open a file in UVTools for more processing, or another external application. (I specify the command line arguments).

It would be nice to be able to "chain" the file from UVTools into other applications, without having to save/close UVTools and manually open the file in the external app.

**Comment by sn4k3** [comment]
I can add that option, allowing to select a application to open the file with

**Comment by sn4k3** [comment]
Proposal:

![image](https://user-images.githubusercontent.com/113281/144358524-8dd4a3e1-7a54-4506-b317-4a74e5f051e6.png)

**Comment by ccatlett1984** [comment]
Amazing, thank you.

Can we get a setting option to specify the name, path to file, and
arguments to pass?

**Comment by sn4k3** [comment]
You will be able to pick the application to execute and provide arguments to pass. On arguments you can pass {0} to indicate the loaded file.

So you can do crazy stuff like: cmd.exe "{0}" "C:\mynewfile.whatever"

**Comment by ccatlett1984** [comment]
Awesome 👍

**Comment by sn4k3** [comment]
Configuration

![UVtools_2021-12-02_20-05-57](https://user-images.githubusercontent.com/113281/144494861-138c44bd-e0ee-46e2-9e36-4c4caa05eeff.png)

**Comment by sn4k3** [comment]
Implemented
