### ISSUE TITLE
[BUG] UVTools does not start under fesh instllation of Windows 11

### ISSUE THREAD

**Issue by MeierAlex** [sn4k3/UVtools#356]
UVTool does not start under Windows 11 N. i also tried st start it from the commandline -> No output.

## System
 - OS: Windows 11 N + Media Extension Pack
 - UVtools version: v2.25.3

**Comment by sn4k3** [comment]
The problem is the Windows **N** variant. Even with Media Extension Pack seens not enough to make OpenCV run.
If you are on a fresh install i recommend you install  the normal version, the non-N and it will fix your problem

**Comment by MeierAlex** [comment]
Thank you very much for your reply - I sadly do not have the opportunity to use an other version than Windos 11N. Do you have a hint for me how I cn get UVTools to work ?

**Comment by sn4k3** [comment]
> Thank you very much for your reply - I sadly do not have the opportunity to use an other version than Windos 11N. Do you have a hint for me how I cn get UVTools to work ?
Would it be possible to simply install OpenCV ?

I have no clue... Others with Windows 10 N + Media Extension Pack also failed to get it to work. It's not UVtools related. 
Your best shot is asking for help on correct repository: https://github.com/emgucv/emgucv/discussions and link with this issue
Something else is failing other than the Media Extension Pack requirement

**Comment by MeierAlex** [comment]
I have started a discussion - thank you very much. it would be a pitty if I could not use you brilliant software any more :/

**Comment by sn4k3** [comment]
> I have started a discussion - thank you very much. it would be a pitty if I could not use you brilliant software any more :/

It will be solved, is a matter of time and discover what is missing...

**Comment by MeierAlex** [comment]
Fixed the problem - you have to install the media extionsions via windows by "Add optional feature" -> "Media Extensions"

**Comment by sn4k3** [comment]
Thanks for discover that, i will update readme accordingly
