### ISSUE TITLE
Phrozen Sonic Mini 4K - memory error

### ISSUE THREAD

**Issue by JasonBelec** [sn4k3/UVtools#368]
App opens, everything works, export to USB for testing, goto to printer, start and Memory Error. Every time, tried playing with settings, no go.

**Comment by sn4k3** [comment]
Upload your file here for i to check

**Comment by JasonBelec** [comment]
[PhrozenSonicMini4K_1.8_2.6_0.2.ctb.zip](https://github.com/sn4k3/UVtools/files/7697548/PhrozenSonicMini4K_1.8_2.6_0.2.ctb.zip)

Had to ZIP it...

**Comment by sn4k3** [comment]
The machine name is wrong, from where do you created that .ctb?
If chitubox you need to select the right machine from the list and not a default created by you

**Comment by JasonBelec** [comment]
Good catch. I loaded the default test file from the manufacturer (Phrozen) which would use Chitubox. I use Mango. 

--

Evil: If I were creating the world I wouldn't mess about with butterflies and daffodils. I would have started with lasers, eight o'clock, Day One!

Jason Belec

**Comment by sn4k3** [comment]
That's a bad pratice. You should always load a sliced file by you, one that you print previous by preference.
Retry with my suggestion and report back.

**Comment by JasonBelec** [comment]
Ok, All good, thanks for your speedy support. I must have missed that did bit of information, my bad.
