### ISSUE TITLE
[FEATURE REQUEST] Layer Import

### ISSUE THREAD

**Issue by nvx** [sn4k3/UVtools#37]
**Is your feature request related to a problem? Please describe.**
As far as I know, the only way to author a photon file from scratch is to use the Photon File Editor tool which is pretty clunky.

**Describe the solution you'd like**
Being able to import new layers (from appropriately sized PNG images) into existing files, or create a new file from a series of images would be super handy to manually create pixel perfect slices.

**Comment by sn4k3** [comment]
That was already on my todo list :)

**Comment by nvx** [comment]
Awesome! What you've done with UVtools so far is amazing. As an exercise I supported and fixed up a really broken model exported from a game for a friend, definitely wouldn't have been able to fix it without UVtools (or remaking the model entirely). I never realised there was anything missing from the Photon File Validator until I checked out UVtools 😅

**Comment by sn4k3** [comment]
You can only know what you are missing if you try different things ;)

**Comment by sn4k3** [comment]
Preview of the tool, if you have more ideas to add just write

![image](https://user-images.githubusercontent.com/113281/92345837-cfde5e80-f0c2-11ea-9447-7ff71d8a4a82.png)

**Comment by nvx** [comment]
Awesome. I assume that it'd support AA by importing files with shades of grey not just black and white pixels yeah?

Also I assume the add button lets you select multiple files at once not just one at a time?

**Comment by sn4k3** [comment]
Yes and Yes :)

**Comment by sn4k3** [comment]
Implemented
