### ISSUE TITLE
[BUG] Inverted brush operation in "Pixel editor"

### ISSUE THREAD

**Issue by g3gg0** [sn4k3/UVtools#399]
Sorry to open another issue :)

## System
 - OS: Windows 10 Version 10.0.19044.1415
 - Slicer: Photon Workshop v2.1.26RC0
 - Printer: Anycubic Photon S
 - UVtools version: 2.27.5

UVtools v2.27.5
Operative system: Microsoft Windows 10.0.19044 X64
Processor: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Processor cores: 12
Memory RAM: 15.23 / 31.94 GB
Runtime: win10-x64
Framework: .NET 5.0.13
AvaloniaUI: 0.10.11
OpenCV: 4.5.4-235

Sreens, resolution, working area, usable area:
1: 1920 x 1200 @ 100% (Primary) (On this)
    WA: 1920 x 1160    UA: 1920 x 1160
2: 1920 x 1200 @ 100%
    WA: 1920 x 1160    UA: 1920 x 1160

Path: C:\Program Files\UVtools

## Describe the bug
When using Drawing tools, rotation angle is inverted between cursor and preview/operation

## To Reproduce
1. Open a file
2. Click on 'Pixel Editor'
3. Select "Line" shape with huge diameter (e.g. 2560)
4. Set rotation to e.g. 30 degree
5. Cursor shows which pixels will get set/cleared
6. Set or clear some pixels (note: the tooltip says "Hold CTRL to clear pixels", but instead you have to right click)
7. The operation will show the operation with an inverted angle

https://www.youtube.com/watch?v=cH9jzrV-Grg

## Expected behavior
preview cursor and operation should match

## Screenshots
![grafik](https://user-images.githubusercontent.com/479231/148465530-f24ed817-5dbd-43e7-8112-93381cf61204.png)
![grafik](https://user-images.githubusercontent.com/479231/148465565-d706a8f8-c6a1-4a94-9bff-5a05b91c0817.png)

**Comment by sn4k3** [comment]
Yes line seens incorrect, while other shapes are ok...

**Comment by sn4k3** [comment]
Fixed
