### ISSUE TITLE
[FEATURE REQUEST] .PM3 files support  

### ISSUE THREAD

**Issue by Finnedsgang** [sn4k3/UVtools#454]
Support for .PM3 files (Anycubic Photon M3 new files)

Needed support for PM3 files, the new format for the Anycubic Photon M3 printers just released from Anycubic. 
Lychee has already the support to these new printers but when sending the files to UV Tools nothing happens.

**Comment by Finnedsgang** [comment]
Don't think there's a version of Photon Workshop compatible with the new format, the latest release fo the software is two years old. Lychee, by the way, has already it.

**Comment by sn4k3** [comment]
They keep updating software, links are just hard to find... Here the link: https://drive.google.com/file/d/1sXP1IIZUzZwKVist6NN_yHK-Q1q85EFz/view?usp=sharing

**Comment by Finnedsgang** [comment]
Nice! thanks, here a pic and the file machine.json
![anycubic](https://user-images.githubusercontent.com/69695968/162784464-49d9cc19-a724-4b45-8737-5891027fb091.PNG)
[AnycubicPhotonM3.zip](https://github.com/sn4k3/UVtools/files/8465964/AnycubicPhotonM3.zip)

**Comment by sn4k3** [comment]
Implemented
