### ISSUE TITLE
[BUG] Pixel Editor button is hidden

### ISSUE THREAD

**Issue by smeshenberglandi** [sn4k3/UVtools#458]
## System
 - OS: [e.g. Windows 10 x64 v20H2]
 - Slicer: 
 - Printer: 
 - UVtools version: 3.3.1 X64

```
1. Go to "UVtools -> Help -> About"
2. Right click on "Copy information" -> "Copy the essential information"
3. Paste that infomation bellow this line:
UVtools v3.3.1 X64
Operative system: Microsoft Windows 10.0.19044 X64
Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Processor cores: 16
Memory RAM: 14.12 / 31.73 GB
Runtime: win10-x64
Framework: .NET 6.0.3
AvaloniaUI: 0.10.13
OpenCV: 4.5.5-237

Sreens, resolution, working area, usable area:
1: 1920 x 1200 @ 125%
    WA: 1920 x 1150    UA: 1536 x 920
2: 2560 x 1440 @ 125% (Primary) (On this)
    WA: 2560 x 1390    UA: 2048 x 1112

Path:       C:\Program Files\UVtools_win-x64_v3.3.1\
Executable: C:\Program Files\UVtools_win-x64_v3.3.1\UVtools.exe

```

## Describe the bug

The button for the pixel editor is hidden behind the preview window.

## To Reproduce
1. On initial launching of the program, this happens.

## Expected behavior

The pixel editor button would be horizontally next to the outline button

## Screenshots

![image](https://user-images.githubusercontent.com/103210433/163209727-0768b5f0-3cd0-468f-beba-f21c952830c8.png)

**Comment by sn4k3** [comment]
This is an old issue, not UVtools related.
It comes from the UI framework and because you use screen scaling of 125%. Switch to 100% solve the problem.
Out of my scope, i already report the bug to the UI framework

**Comment by sn4k3** [comment]
Fixed
