### ISSUE TITLE
[FEATURE REQUEST] Apply mutations to a region of interest selection

### ISSUE THREAD

**Issue by pteal** [sn4k3/UVtools#49]
I would find it extremely useful if I could apply different mutators to different areas of my sliced images. For example, I would like to test different erode parameters or pixel dimming settings at the same time during a single print. Here is how I envision an ideal workflow:

1) Load up my build plate with a dozen identical test models, slice it, and then load it into UVtools.

2) Use a marquee selection tool within UVtools to select an area of the build plate.

3) Use the mutator tools as normal, but only apply the changes to the selected area.

4) Repeat items 2 and 3 for each area of the build plate pertaining to each test model.

5) Print all test models at once, making it fast and easy to evaluate the results.

A simple rectangular selection would probably be sufficient for most use cases, but the ability to create elliptical or arbitrary selections would be even more powerful.

**Comment by sn4k3** [comment]
Implemented
