### ISSUE TITLE
ctbv4 encryption message not displaying correctly

### ISSUE THREAD

**Issue by frozenowni** [sn4k3/UVtools#537]
Hi,
I recently got a saturn 2 and therefore started using ctbv4 files...

The informative message upon opening was not displayed correctly on my pc. I use a 15" screen in full hd 16:9.
it was only saying "informative message ..."
I only found out about the rest when trying to select all by triple-clicking...

Can you maybe enlarge the message window so all users see the background info regarding the ctbv4 fileformat.

Thanks for the great tool btw!

BR Jonas

**Comment by sn4k3** [comment]
Also reported here: https://www.facebook.com/groups/uvtools/posts/740410317068474

This is a bug with message box library (external from UVtools).
Will be fixed on next release with PR: https://github.com/AvaloniaCommunity/MessageBox.Avalonia/pull/113

**Comment by frozenowni** [comment]
Ok great thx

**Comment by sn4k3** [comment]
Fixed
