### ISSUE TITLE
[BUG] PerLayerOverride always 0

### ISSUE THREAD

**Issue by LigaMoscow** [sn4k3/UVtools#563]
Hello. Today I noticed that in the new release PerLayerOverride is always 0. I tried all known slicers. Any layer settings. PerLayerOverride always 0. Old versions of UVtools work fine. Hope you fix it soon. Anycubic Photon Mono X Printer

**Comment by sn4k3** [comment]
PerLayerOverride is auto set and will only change on datalist after you save and reload the file, from slicer will come 0 by default,.
