### ISSUE TITLE
[BUG] Huge problem for release 3.6.8. It doesn't start....

### ISSUE THREAD

**Issue by tecchese** [sn4k3/UVtools#571]
Release 3.6.8 does not start...simply...
See pics, previous version (3.6.7) works yet...

![Cattura](https://user-images.githubusercontent.com/107458958/193761190-13eaa7fd-0e97-490c-95c2-7a0f70a0ac31.JPG)
![Cattura2](https://user-images.githubusercontent.com/107458958/193761192-4037e737-d94b-42e5-b216-d8a350078344.JPG)
![Cattura34](https://user-images.githubusercontent.com/107458958/193761197-e70138ae-836e-471a-9c0d-7d77c36ca44d.JPG)

**Comment by sn4k3** [comment]
May be related with https://github.com/sn4k3/UVtools/issues/566

Try to uninstall and install, or repair by rerun installer

**Comment by scheini79** [comment]
> May be related with #566
> 
> Try to uninstall and install, or repair by rerun installer

That fixed it for me, just rerun the installer and choosed repair.

**Comment by tecchese** [comment]
yes, it is the unique solution...uninstalled, rebooted e installed...

**Comment by sn4k3** [comment]
Fixed v3.7.0
