### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by smulevit** [sn4k3/UVtools#576]
## System
 - OS: [e.g. Windows 11 x64 v22H2]
 - Slicer: CHITUBOX
 - Printer: ELEGOO Mars 3 PRO
 - UVtools version: 3.6.8 X64

```
1. Go to "UVtools -> Help -> About"
2. Right click on "Copy information" -> "Copy the essential information"
3. Paste that infomation bellow this line:

```
UVtools v3.6.8 X64
Operative system: Microsoft Windows 10.0.22623 X64
Processor: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor cores: 8
Memory RAM: 7.54 / 15.71 GB
Runtime: win10-x64
Framework: .NET 6.0.9
AvaloniaUI: 0.10.18
OpenCV: ???

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100%
    WA: 1920 x 1080    UA: 1920 x 1080
2: 3840 x 2160 @ 250% (Primary) (On this)
    WA: 3840 x 2160    UA: 1536 x 864

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe

## Describe the bug
 Received a warning saying "UVtools cannot run due one or more missing dependencies". I followed instructions to install Windows Feature Pack, then, when I went to check Media Extensions in Windows Features, I cannot find "Media Extensions".

**Comment by sn4k3** [comment]
https://github.com/sn4k3/UVtools/issues/571
