### ISSUE TITLE
[BUG] error on loading cws files.

### ISSUE THREAD

**Issue by rflorean** [sn4k3/UVtools#577]
## System
 - Windows 10 x64 v20H2
 - Slicer: novamaker v.2.6.6 64bit
 - Printer: nova3d bene4
 - UVtools version: 3.6.4

```
1. Go to "UVtools -> Help -> About"
2. Right click on "Copy information" -> "Copy the essential information"
3. Paste that infomation bellow this line:

System.IO.FileLoadException: Layer 0 not found
   at UVtools.Core.FileFormats.FileFormat.DecodeLayersFromZipRegex(ZipArchive zipArchive, String regex, IndexStartNumber layerIndexStartNumber, OperationProgress progress, Func`3 matGenFunc) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\FileFormats\FileFormat.cs:line 3645
   at UVtools.Core.FileFormats.CWSFile.DecodeInternally(OperationProgress progress) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\FileFormats\CWSFile.cs:line 841
   at UVtools.Core.FileFormats.FileFormat.Decode(String fileFullPath, FileDecodeType fileDecodeType, OperationProgress progress) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\FileFormats\FileFormat.cs:line 3416
   at UVtools.WPF.MainWindow.<>c__DisplayClass107_0.<ProcessFile>b__1() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 1367
```

## Describe the bug
On open file cws the error comes out.

**Comment by sn4k3** [comment]
Layer 0 not found on the file.
Include the file that caused that so i can look

**Comment by sn4k3** [comment]
The problem looks like with filename... If you are using a number on the file end name that raise problem with UVtools. Do not use file with numbers in the end

**Comment by rflorean** [comment]
Thanks for your reply. I send you what happens:
first test cws sliced with novamaker
second test cws sliced with lycheeslicer

Regards
________________________________
Da: Tiago Conceição ***@***.***>
Inviato: domenica 9 ottobre 2022 23:21
A: sn4k3/UVtools ***@***.***>
Cc: rflorean ***@***.***>; Author ***@***.***>
Oggetto: Re: [sn4k3/UVtools] [BUG] error on loading cws files. (Issue #577)


The problem looks like with filename... If you are using a number on the file end name that raise problem with UVtools. Do not use file with numbers in the end

**Comment by sn4k3** [comment]
Attachments via email don't work here. You have to use github directly on web browser

**Comment by rflorean** [comment]
https://user-images.githubusercontent.com/42885977/194930830-39deb8c5-067a-4033-9b1c-8cdc5dfd87f7.mp4


https://user-images.githubusercontent.com/42885977/194930841-db1e0eb5-eb2d-4d3a-9dd5-18cd091482e2.mp4

cws created with novamaker doesn't work; cws created with lycheeslice does work! same content

**Comment by rflorean** [comment]
original stl file
[_221010_ganasce_mobili_H110_4_centrali_2_2_BCDEF_55_10_gradi_passo_9.zip](https://github.com/sn4k3/UVtools/files/9748228/_221010_ganasce_mobili_H110_4_centrali_2_2_BCDEF_55_10_gradi_passo_9.zip)

**Comment by sn4k3** [comment]
I need the sliced files (.cws) to explore the contents.
I confirm that .cws from original slicer does have problem with UVtools which will be fixed on next release, but the error I see from your first video looks like the problem with filename. Either way both will be fixed on next release.

**Comment by rflorean** [comment]
this was produced with novamaker: [test_uvtools.zip](https://github.com/sn4k3/UVtools/files/9751514/test_uvtools.zip)
the following file has been produced with lycheeslicer
[second_test_with_LycheeSlicer.zip](https://github.com/sn4k3/UVtools/files/9751523/second_test_with_LycheeSlicer.zip)

**Comment by rflorean** [comment]
both have same origin, so they should be identical but it is not true.

**Comment by sn4k3** [comment]
Here the problem, as told it's a file name problem, it have a number in the end: "_221009_ganasce_mobili_H110_4_centrali_2_2_BCDEF_55_10_gradi_passo_9" that cause to parse layers incorrectly.

![WinRAR_Re3xD5W5fo](https://user-images.githubusercontent.com/113281/195064174-c9f4ba6e-6252-4223-8d0a-2e173807e398.png)

**Comment by rflorean** [comment]
Crazy! Stl file name has a number at the end! In my life I've written a lot of programs, but this looks me crazy: but it is true. I've changed stl file name, created with novamaker new cws, and then, oops, uvtools reads the cws file. This issue doesn't happen with lycheeslice. Thanks. RegardsIl 11 Ott 2022 12:16, Tiago Conceição ***@***.***> ha scritto:
Here the problem, as told it's a file name problem, it have a number in the end: "_221009_ganasce_mobili_H110_4_centrali_2_2_BCDEF_55_10_gradi_passo_9" that cause to parse layers incorrectly.

**Comment by sn4k3** [comment]
>  This issue doesn't happen with lycheeslice.

Because lychee uses no filename as layer image, it uses lychee000.png
![image](https://user-images.githubusercontent.com/113281/195090799-abc395e9-5b21-4045-b2be-892df58cc139.png)

**Comment by rflorean** [comment]
👍

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sn4k3** [comment]
Fixed
