### ISSUE TITLE
[FEATURE REQUEST] .PM3R files support

### ISSUE THREAD

**Issue by hkjytkd** [sn4k3/UVtools#587]
Support for .PM3R files (Anycubic Photon M3 Premium new files)

Needed support for PM3R files, the new format for the Anycubic Photon M3 Premium printers just released from Anycubic.
CHITUBOX & TANGO has already the support to these new printers but when sending the files to UV Tools nothing happens.

**Comment by sn4k3** [comment]
Chitubox v1.9.4 don't have it
Anycubic photon workshop v2.2.16 don't have it
Google search gives very few results (almost to none)
Anycubic.com website don't have it
I can only find it on latest Tango

Is the printer available to the public at the moment?

**Comment by hkjytkd** [comment]
Sorry, chitubox does not support it, but tango v 2.11.99.48 and anycubic photo workshop v2.2.19 support it，the machine is now on sale。

**Comment by hkjytkd** [comment]
I bought the installation package that came with the device.

How can I send it to you?

**Comment by sn4k3** [comment]
Upload to a web service, eg https://wetransfer.com and post the link here

**Comment by hkjytkd** [comment]
https://we.tl/t-ea68hlmEFn

**Comment by hkjytkd** [comment]
Please try to download!

**Comment by sn4k3** [comment]
It works, will be in the next release

**Comment by hkjytkd** [comment]
thx！！！

**Comment by sn4k3** [comment]
Implemented
