### ISSUE TITLE
[BUG] Longer Orange 30 and Lychee Slicer

### ISSUE THREAD

**Issue by calipzo** [sn4k3/UVtools#59]
**Describe the bug**
When I open a file silced in Lychee Slicer it looks incorrect.

**To Reproduce**
1. Install Lychee Slicer (free version; v3.0.11 at this time).
2. Add Longer Orange 30 printer.
3. Slice proposed model with default settings.
4. Open it in UV Tools.

(my file in the bottom)

**Screenshots**
![image](https://user-images.githubusercontent.com/2325646/93021500-92f6f800-f5eb-11ea-8955-a4b8d8b085c0.png)

**Files**
[Here is my *.lgs30 file](https://mega.nz/file/bE0yEQ6Y#0iLsrYnghKpptmU1XB4L3HXvhiZ2zvYvu4tLH2znohI) sliced with Lychee Slicer (if needed).

**Comment by sn4k3** [comment]
Resolution is fliped (bad configuration on slicer, invert resolutions).

**Comment by calipzo** [comment]
It's very strange. I have [found on my flash old sliced file](https://mega.nz/file/kk5RGJZQ#2hgK-edaw9OGWPRtEZlyNUKGmHeQXr9h_PD4UEUoDdw) (sliced with Chitubox) - and it have the same problems. The file has been printed many times without problems.

![image](https://user-images.githubusercontent.com/2325646/93024748-4b7b6680-f601-11ea-8b29-5767e0238676.png)

**Comment by sn4k3** [comment]
Can you show your chitubox printer configuration dialog?

**Comment by sn4k3** [comment]
This is what i got from pre-configurated machines on chitubox. As you can see your X is fliped with Y
UVtools shows: 2560x1440 and the correct is the flip value
![image](https://user-images.githubusercontent.com/113281/93024787-e455b600-f5f0-11ea-9f47-b9962677afa9.png)

**Comment by sn4k3** [comment]
Can you send me a old file sliced with chitubox?

**Comment by calipzo** [comment]
Old file: [download here](https://mega.nz/file/kk5RGJZQ#2hgK-edaw9OGWPRtEZlyNUKGmHeQXr9h_PD4UEUoDdw). I have sliced it 4+ months ago. At the time, both the Chitubox and the plugin were older versions.

In Chitubox I use standard settings except exposure time and layer height.
![image](https://user-images.githubusercontent.com/2325646/93025237-f3defa00-f604-11ea-87a4-a6fc330578e5.png)

**Comment by sn4k3** [comment]
Yes that file is flipped too, the implementation was based on new chitubox version + plugin. Can you try that on your machine just to confirm?

**Comment by calipzo** [comment]
Ok, i will report.

**Comment by vknvkz** [comment]
Hi. Same problem with ChituBox 1.6.5.1 and Longer3D plugin. Default Chutu profile for Orange30 printer was used

![uv0822lgs30](https://user-images.githubusercontent.com/71479853/93552553-e75af880-f99a-11ea-8db5-acb7ac55a9d1.jpg)
[_20x20x20.lgs30.zip](https://github.com/sn4k3/UVtools/files/5243222/_20x20x20.lgs30.zip)

**Comment by sn4k3** [comment]
Thats so strange, can you point me out the URL of plugin you are using for LGS?

**Comment by sn4k3** [comment]
In meanwhile here's a compiled version with XY instead of YX: https://easyupload.io/k0q599
Use that while i try to discover why my chitubox+plugin gave me good results with YX, which never made sense in first place

**Comment by vknvkz** [comment]
> Thats so strange, can you point me out the URL of plugin you are using for LGS?

I was using V1.2 plugin come on usb flash with printer.
![lgs30v12](https://user-images.githubusercontent.com/71479853/93557508-59d0d600-f9a5-11ea-8926-920039815e57.jpg)

I found newer V1.4 plugin: https://drive.google.com/drive/folders/1uMnSBDKeK9if6TdWSsscwQ9E6BxCG6rK?fbclid=IwAR0gWYL_AOq1SRZiQqV2XjSR14KmszEzrn_3I0Z9Hh_qnWu17yBRTlNC5iU

It work fine with original 0.8.2.2 version.

(V1.2 plugin must be deleted first, do not import V1.4 over V1.2!)

**Comment by sn4k3** [comment]
What a mess they did... I'm gona fix this by put a auto resolution flip on code, it will work for both cases

**Comment by sn4k3** [comment]
Implemented
