### ISSUE TITLE
CLI option to specify thumbnail png or thumbnail layer

### ISSUE THREAD

**Issue by jimb15122** [sn4k3/UVtools#599]
Please add a command line option to allow specification of a layer number to use as a thumbnail, or a png file name.  If a thumbnail already exists, replace it.

This would be useful to overcome the limitation in some slicers (Prusa) where the CLI versions do not support thumbnail generation.

The icon in the GUI to replace the thumbnail should also have the option to use the layer in the current view as the thumbnail. 

Keep up the fantastic work!!

**Comment by sn4k3** [comment]
Can do.

![image](https://user-images.githubusercontent.com/113281/200107617-5ad7a429-21aa-492c-aec0-41080320b0b2.png)

**Comment by sn4k3** [comment]
Implemented
