### ISSUE TITLE
[BUG] Unparsable for errors sl1 file

### ISSUE THREAD

**Issue by Nume1977** [sn4k3/UVtools#6]
After changing the Nova3D Elfin printer settings, i resaved the sl1 file, but now it is unparsable for issues  .

**To Reproduce**
1. Open the attached file
2. Goto Issues tab
3. "Error while trying to parse issues" pops up

[Capa_quadrada_DMG.zip](https://github.com/sn4k3/UVtools/files/4837480/Capa_quadrada_DMG.zip)

**Comment by sn4k3** [comment]
It seens you change resolution and image convertion fails without a reason... Anyway this is fixed with new version (not released yet), but you can grab it here: https://easyupload.io/o7z3d4
It will solve your problem and others more

**Comment by Nume1977** [comment]
Fixed, now parses the file!
