### ISSUE TITLE
[BUG] No print in 3.8.1

### ISSUE THREAD

**Issue by dpeet** [sn4k3/UVtools#601]
## System
 - OS: MacOS Ventura
 - Slicer: PrusaSlicer
 - Printer: MonoX 6k
 - UVtools version: 3.8.1

## Describe the bug
I saw an upgrade available for 3.8.1.  Upgrading I saw the same error as show https://github.com/sn4k3/UVtools/issues/431#issuecomment-1304495319, but it was able to start anyway.  I sliced and printed a file, and nothing actually printed.  downgrading to 3.8.0 worked as expected.

**Comment by sn4k3** [comment]
Nothing serious changed on 3.8.1. But i noticed an strange bug while upgrading on Linux which can also affact mac on the auto run.
Can you upgrade via `bash -c "$(curl -fsSL https://raw.githubusercontent.com/sn4k3/UVtools/master/Scripts/install-uvtools.sh)"` and retry?
