### ISSUE TITLE
[FEATURE REQUEST] Improvements to pixel editor

### ISSUE THREAD

**Issue by theloveofcode** [sn4k3/UVtools#604]
First off, I LOVE UVtools and I recommend it a lot. However, I have some ideas that would make the Pixel Editor easier to use and more possibly more performant.

1. Remember my brush choices. Right now, when I close the application, my brush choices are lost.
2. (Perhaps this could be configurable) Don't paint green additions over white pixels, and don't paint red subtractions over black pixels, when antialiasing isn't in use.
3. Collapse operations. If I paint over the same area green, red, green, red, green, red, you'll see that the operation count grows dramatically. This can be collapse to only list/compute the final value of a given pixel. (Maybe only applicable when antialiasing isn't in use.)
4. Introduce the option to draw lines - Most of the time, I'm just trying to draw skinny lines to connect islands, or to drill out tubes for suction cups, etc. Especially when drawing on many layers at once, the performance is pretty bad and my "lines" end up janky. If I could just click to set the starting vertex, click to select the ending vertex, and have the line created for me, it would be a better experience.

I love this application! I pretty much never have failed prints now. Thank you!

**Comment by sn4k3** [comment]
Profiles are now implemented
