### ISSUE TITLE
[FEATURE REQUEST] More Calibration models for Exposure range finder

### ISSUE THREAD

**Issue by whatsforbreakfast** [sn4k3/UVtools#605]
Love the exposure time range finding test but would be great if we could print other tests using it like Amerilabs Town or Cones of Calibration, or any custom stl we want.

**Comment by sn4k3** [comment]
You can. 
Slice the model you want and open in UVtools.
Go to calibration tool and use the last section: Pattern model.
It will pattern your sliced model up to the defined exposure settings

**Comment by whatsforbreakfast** [comment]
Epic!! I dunno how I missed that, you rock <3
