### ISSUE TITLE
[BUG] Missing parts on PCB exposure tool

### ISSUE THREAD

**Issue by VersusJH** [sn4k3/UVtools#607]
Hi! Thank you for this tool and thanks in advance for any help you'll be able to give me.

## System
 - OS: Arch Linux
 - Slicer: X
 - Printer: Anycubic Mono 4k
 - UVtools version: 3.8.3 Appimage

```
UVtools v3.8.3 X64
Operative system: Linux 6.0.8 #1 SMP PREEMPT_DYNAMIC Tue Nov 15 16:04:11 CET 2022 X64
Processor: AMD Ryzen 7 3700X 8-Core Processor
Processor cores: 16
Memory RAM: 7.81 / 15.55 GB
Runtime: arch-x64
Framework: .NET 6.0.11
AvaloniaUI: 0.10.18
OpenCV: 4.6.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100% (Primary)
    WA: 1920 x 1051    UA: 1920 x 1051

Path:       /tmp/.mount_uvtoolvV3B59/usr/bin/
Executable: /tmp/.mount_uvtoolvV3B59/usr/bin/UVtools
Loaded file: base.pwma [Version: 516] [Class: PhotonWorkshopFile]

```

## Describe the bug

I am trying to generate a .pwma file for my printer from a .gerber file, using the PCB exposure tool. Howver, only the upper left corner of the circuit is contained in the generate file, while the rest of the circuit is missing.

## To Reproduce

1. Open file "base.pwma" containing base settings for my printer
2. Open the PCB exposure tool and load the test.gbr file.
3. With any setting (I have not observed any differences) click "PCB exposure" to run the tool
4. Corner of PCB is shown, but not the rest.

## Expected behavior

I would expect the whole PCB to be imported - see attached screenshots.

## Screenshots

![PCB full](https://user-images.githubusercontent.com/44574601/202661635-a70a7f72-c65d-4b51-b8ac-ef64c7781406.png)

![Result](https://user-images.githubusercontent.com/44574601/202661613-66acab6d-340e-457d-b6a8-2677e493c539.png)

## Files

Had to zip them to upload them to github. Contains aforementioned base.pwma and test.gbr

[bugfiles.zip](https://github.com/sn4k3/UVtools/files/10039787/bugfiles.zip)

---

Thank you again, an have a good day!

**Comment by sn4k3** [comment]
Nothing wrong.
You just placed your PCB far from origin (0,0).
UVtools place the board exactly on the coordinates you set in design.

![image](https://user-images.githubusercontent.com/113281/202784412-058873f2-15e0-4acb-906b-e79704e412e5.png)

On CAD move your PCB to 0,0 or near it to make it inside your printer build size. Still if it exceed LCD dimensions it will be cut

**Comment by comato** [comment]
I have same issue with gerber file... "Missing parts". Gerber is generated from EasyEDA (basic version). Green traces on picture are from Kicad gerber viewer, white traces is screenshot from UVTools.
![2022-11-22_020226](https://user-images.githubusercontent.com/24967566/203189435-176f3fa5-e058-4e3f-8b47-b4a900faea34.jpg)
[Gerber_TopLayer.zip](https://github.com/sn4k3/UVtools/files/10061671/Gerber_TopLayer.zip)

**Comment by sn4k3** [comment]
@comato can you prepare a minimal file only with that marked area?

**Comment by comato** [comment]
I prepared it, same... gerpber is in ZIP
[Gerber_TopLayer.zip](https://github.com/sn4k3/UVtools/files/10065133/Gerber_TopLayer.zip)
![2022-11-22_085619](https://user-images.githubusercontent.com/24967566/203257659-29f80a77-f8c0-45bb-aaa8-0e50f24fdec9.jpg)

**Comment by comato** [comment]
Nice, thank you :)

**Comment by sn4k3** [comment]
Fixed
