### ISSUE TITLE
[BUG] New W/S hotkeys eat keystrokes inside text input field

### ISSUE THREAD

**Issue by tofof** [sn4k3/UVtools#62]
**Describe the bug**
The 'text' pixel editor can no longer receive the W or S keystrokes when typing in the text field.

**To Reproduce**
1. Pixel editor -> Text -> Text: 
2. Type 'qwer asdf'
3. See that you've only typed 'qer adf'

Home/end work as expected for text field, but also jump to top/bottom layer at same time.

**Expected behavior**
All (?) hotkeys disabled while typing in text field

**Desktop (please complete the following information):**
 - OS: Win 10 Pro x64 1803
 - UVTools 0.8.2.2

Keep up the great work! I was thrilled by the region-of-interest addition.

**Comment by sn4k3** [comment]
Confirmed, will be addressed on next patch

**Comment by sn4k3** [comment]
Fixed
