### ISSUE TITLE
[Bug] Suction cup area not calculated correctly in issue analysis

### ISSUE THREAD

**Issue by klauskopec** [sn4k3/UVtools#621]
### System

```Text
UVtools v3.9.2 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor cores: 8
Memory RAM: 12.73 / 15.86 GB
Runtime: win10-x64
Framework: .NET 6.0.11
AvaloniaUI: 0.10.18
OpenCV: 4.6.0

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: Alchemists_Shelf_-_Top_Peg.ctb [Version: 2] [Class: ChituboxFile]
```

### Printer and Slicer

- Printer: Elegoo Saturn
- Slicer: Lychee

### Description of the bug

In the issue analysis, suction cups are reported with area size 0 instead of the correct size. This used to show a non-zero number until a few versions ago.

### How to reproduce

load any file with suction cups and run issue analysis

**Comment by sn4k3** [comment]
> How to reproduce
load any file with suction cups and run issue analysis

Does not happen in my files. Please submit a file with the problem.

**Comment by klauskopec** [comment]
Here's a simple example. File was created using Lychee 5.0.001, but I already had the issue with Lychee 4.x. The issues was not there a few months ago, but then started to come up and I think it was after I updated UVTools at the time, but I don't fully recall.

[cylinder.zip](https://github.com/sn4k3/UVtools/files/10216294/cylinder.zip)
![uvtools bug zero size sucction cup](https://user-images.githubusercontent.com/7880831/207277162-f34808c5-dacd-43ec-95fc-fc1e06cb4b32.png)

**Comment by sn4k3** [comment]
Found the problem, will fix in next release

**Comment by sn4k3** [comment]
Fixed
