### ISSUE TITLE
[Bug] macOS M1 arm64 - 3.9.3 - Package damaged or incomplete

### ISSUE THREAD

**Issue by mawburn** [sn4k3/UVtools#625]
### System

```Text
- UVTools v3.9.3 arm64
- macOS Ventura 13.0.1
  - Apple M1
```
<img width="251" alt="Screenshot 2022-12-15 at 6 28 38 PM" src="https://user-images.githubusercontent.com/2829924/207988366-5cc3004d-0db7-446a-bbac-5bb22bba5226.png">

### Printer and Slicer

n/a

### Description of the bug

Doesn't run or install from command line or run through the zip. 

<img width="568" alt="Screenshot 2022-12-15 at 6 25 20 PM" src="https://user-images.githubusercontent.com/2829924/207987951-20eeb94d-c288-49e7-8a8b-00dd9df9e220.png">
<img width="382" alt="Screenshot 2022-12-15 at 6 25 59 PM" src="https://user-images.githubusercontent.com/2829924/207987975-b98e0e89-7b84-4979-814f-780493eb9bb6.png">

It actually also caused an issue with the old version (3.9.2) when I tried to reinstall it, where I have to resign it through the command line. 

```cmd
codesign --force --deep --sign - ./UVtools.app
```

Not sure if it's related, but figured it was worth a mention.

### How to reproduce

Tried to install from:

```cmd
bash -c "$(curl -fsSL https://raw.githubusercontent.com/sn4k3/UVtools/master/Scripts/install-uvtools.sh)"
```

And the .zip file. 

https://github.com/sn4k3/UVtools/releases/download/v3.9.3/UVtools_osx-arm64_v3.9.3.zip

**Comment by sn4k3** [comment]
I have checked, and in fact the `arm64` package miss the UVtools binary, I dont know why... All others packages are fine.
I have reupload the arm64, please check.

Note: The auto-installer script does the codesign for you. No need to do manually.

**Comment by mawburn** [comment]
@sn4k3 that was fast! 

I forgot to mention that I originally tried downloading from the app itself, which I just retried and it works great! Thanks!
