### ISSUE TITLE
Prusa SL1 or SL1S files appear to be corrupted when importing

### ISSUE THREAD

**Issue by DanielDC88** [sn4k3/UVtools#627]
### System

```Text
UVtools v3.9.1 X64
Operative system: Microsoft Windows 10.0.19044 X64
Processor: AMD Ryzen 9 3900X 12-Core Processor            
Processor cores: 24
Memory RAM: 8.06 / 15.93 GB
Runtime: win10-x64
Framework: .NET 6.0.11
AvaloniaUI: 0.10.18
OpenCV: 4.6.0

Sreens, resolution, working area, usable area:
1: 2560 x 1440 @ 100% (Primary) (On this)
    WA: 2560 x 1400    UA: 2560 x 1400
2: 1080 x 1920 @ 100%
    WA: 1080 x 1880    UA: 1080 x 1880


Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: Rookv_fixed1.sl1 [Version: 0] [Class: SL1File]
```

### Printer and Slicer

- Printer: Prusa SL1
- Slicer: Prusaslicer 2.5.0

### Description of the bug

When I export the part from Prusaslicer as an SL1 or SL1S folder and import into UV tools, the image privew does not show the file correctly:
![image](https://user-images.githubusercontent.com/28685670/208298609-61a09d65-f8ec-4e0b-a3c3-00c5dfa8e0cf.png)

### How to reproduce

export sl1 from prusaslicer
open in uvtools

### Files

[Rookv_fixed1.zip](https://github.com/sn4k3/UVtools/files/10253828/Rookv_fixed1.zip)

**Comment by sn4k3** [comment]
You need to install and use my printer (UVtools Prusa SL1). Because the original preset have the resolution flipped on settings.
