### ISSUE TITLE
[FEATURE REQUEST] Possible overhang detection

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#64]
Awesome little tool! I was using PhotonFileValidator but this is miles ahead of that one. I just got a new cheap creality ld002-r and the lack of tools is troublesome, it is like china is overtaking the market from the start with some working/cheap but also buggy solutions so it is inspiring to see some tools like this popping

**Describe the solution you'd like**
The island and resintraps are cool, but "possible overhangs" would be the most useful type of detection. Basically any "next/previous" big groups of pixels could be a possible weakpoint.

**Screenshots**
![image](https://user-images.githubusercontent.com/1091420/94054733-4924c380-fddc-11ea-920a-42a42ed8e7ea.png)

BTW the creality printer, for the price is surprising, I mean the firmware and chitubox has some bugs but nothing compared to my first fdm, that was a 2k USD makerbot!

**Comment by sn4k3** [comment]
Cheap or expensive printers are independent from slicer result. If you use a bad slicer on a top printer the result will be bad no matter what. Also they must be tunned for each object, there's no 1 setting to rule-them-all

About overhangs i can implement a detection without fix for them. They must be deal on slicer, on PrusaSlicer you can configure the overhang threshold.

The objects you show on sample don't seen a problem to me on a real print, but a huge mass will

**Comment by eried** [comment]
Well, as I said it is just my first days with the printer, so it is fine to use all ready to use stuff I can to start. If I start creating my own profile in PS I might just find problems that do not actually exist. And, yes, those areas wont produce any problem, I agree a bigger one will, I was just trying to provide a example.

**Comment by sn4k3** [comment]
> If I start creating my own profile in PS I might just find problems that do not actually exist. 
Go UVtools -> Help -> Install profiles. Check if you printer is there

**Comment by eried** [comment]
oh wow! nice. I will try it. On a super quick look, Chitubox supports seem to be a bit ahead prusaslicer

**Comment by sn4k3** [comment]
That will change on next PS release. But slicing quality is better

**Comment by sn4k3** [comment]
Implemented

**Comment by eried** [comment]
Hi, what is the concept behind this? I mean I am trying to understand how it works, for example if you check this:
https://www.screencast.com/t/UhWAGUD0

There is actually no overhang right? it is just a solid block but overhang is detected. 🤔

**Comment by sn4k3** [comment]
That may be a bug, can you send me your file?

**Comment by sn4k3** [comment]
I also have an ideia, chitubox new version are creating fade pixels, it seens like white but they arent.
Can you try run a 1 or 2 GapClosing iterations with Morph or layer repair?
Then redetect overhangs

**Comment by sn4k3** [comment]
Just confirmed, is what i think.

![image](https://user-images.githubusercontent.com/113281/94722630-7d096700-034f-11eb-9a6b-cd0c956d2a1e.png)

Look that layer, one part of object is less white. Creating a overhang. I will threshold layer before to fix this

**Comment by eried** [comment]
oh you are right. Here is the file just in case: https://mega.nz/file/q88UCYTK#EKir_LNycnywTTfznP1xlmBbADbQwRzRUHv1i74ucc4

I do not see a way to disable this in Chitubox, antialiasing is ON but on 0 by default. I know you recommended prusa slicer, but the supports are so nice on chitubox :/

**Comment by sn4k3** [comment]
I already fix the issue, will be avaiable on next patch

**Comment by eried** [comment]
nice! I am trying to print a big [case](https://www.thingiverse.com/thing:4260973) and using your tool for learning why each print has small defects (deformations on the result) is the only tool I was able to find

**Comment by sn4k3** [comment]
deformations can be many variables out of UVtools scope, like LCD, LEDs, Z...

**Comment by eried** [comment]
yeah I know, I am just using uvtools for trying to find the culprit. It is usually on the thin "overhangs" even if they are small

**Comment by sn4k3** [comment]
BTW uvtools by default are set to find overhangs larger than 5mm (the 49px you saw on settings)
