### ISSUE TITLE
[BUG] Blurry UI

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#65]
**Describe the bug**
UI is blurry on high dpi configurations

**To Reproduce**
Open the app on any machine with a dpi setting different than 100%, i.e. any new 4k laptop (150% or 200% is the usual default) 

**Screenshots**
Up one is with high-dpi forced, low one is the blurry current one.
![image](https://user-images.githubusercontent.com/1091420/94143522-3c51af80-fe70-11ea-8006-0ee72697f93a.png)

**Additional context**
The solution is not as simple as adding:
  ```
  <System.Windows.Forms.ApplicationConfigurationSection>
        <add key="DpiAwareness" value="PerMonitorV2" />
        <add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
    </System.Windows.Forms.ApplicationConfigurationSection>
```
to `app.config`, there are hardcoded sizes for the controls that dont scale properly :/

**Comment by sn4k3** [comment]
yep that will happen when you scale windows or accept visual fixes from windows, thats a common problem with many apps.
I'm droping GUI development in favour of new GUI that support multi-os, is being rewritten and this problem will go away on that version

**Comment by sn4k3** [comment]
Will fix on v1
