### ISSUE TITLE
[BUG] No shortcuts on programs/desktop when using UVtools_X.X.X.X.msi

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#66]
**Describe the bug**
There is no icon created anywhere to access UVtools.

**To Reproduce**
1. Install UVtools_v0.8.2.4.msi
2. You need to execute "C:\Program Files (x86)\UVtools\UVtools.exe" directly

**Expected behavior**
Icon should be create on desktop and/or start menu

**Comment by sn4k3** [comment]
For me is working, both menu and desktop shortcut are present

![image](https://user-images.githubusercontent.com/113281/94155977-77a3ac80-fe77-11ea-8027-ef155ce37cf9.png)

![image](https://user-images.githubusercontent.com/113281/94156041-87bb8c00-fe77-11ea-9c2e-45966e9e873b.png)

**Comment by eried** [comment]
Oh weird, maybe is an older release? I tried in 3 machines. No icon created on any of them.

**Comment by sn4k3** [comment]
I will check latter with diferent msi

**Comment by eried** [comment]
I mean the icon was not removed after updating. You can see in Windows Sandbox that there is no new icon after you run the msi: 
![image](https://user-images.githubusercontent.com/1091420/94158362-978c9d80-fe82-11ea-823e-624c70164ea3.png)

**Comment by sn4k3** [comment]
Cath the problem, will be fixed on a next patch

**Comment by sn4k3** [comment]
Fixed

**Comment by eried** [comment]
Awesome, thanks!
