### ISSUE TITLE
Error opening the file - System.IO.FileLoadException: Malformed file: prusaslicer.ini is missing. 

### ISSUE THREAD

**Issue by Steve566074** [sn4k3/UVtools#681]
### System

```Text
UVtools v3.12.1 X64
Operative system: Microsoft Windows 10.0.22621 X64
Processor: AMD Ryzen 3 3250U with Radeon Graphics         
Processor cores: 4
Memory RAM: 4.74 / 5.94 GB
Runtime: win10-x64
Framework: .NET 6.0.15
AvaloniaUI: 0.10.18
OpenCV: 4.6.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100%
    WA: 1920 x 1032    UA: 1920 x 1032
2: 1920 x 1080 @ 100% (Primary) (On this)
    WA: 1920 x 1032    UA: 1920 x 1032


Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
```

### Printer and Slicer

- Printer:  Prusa SL1S
- Slicer: Lychee V5.1

### Description of the bug

Getting the following error message when trying to open an SL1S file.

System.IO.FileLoadException: Malformed file: prusaslicer.ini is missing.
   at UVtools.Core.FileFormats.SL1File.DecodeInternally(OperationProgress progress) in UVtools.Core\FileFormats\SL1File.cs:line 656
   at UVtools.Core.FileFormats.FileFormat.Decode(String fileFullPath, FileDecodeType fileDecodeType, OperationProgress progress) in UVtools.Core\FileFormats\FileFormat.cs:line 3617
   at UVtools.WPF.MainWindow.<>c__DisplayClass110_0.<ProcessFile>b__1() in UVtools.WPF\MainWindow.axaml.cs:line 1342

### How to reproduce

File - Open - select file from PC directory.

Tried with several files.

### Files

[Examples of file that error.zip](https://github.com/sn4k3/UVtools/files/11061832/Examples.of.file.that.error.zip)
![Screenshot 2023-03-24 120929](https://user-images.githubusercontent.com/128797453/227517685-bde76b05-d85e-45c8-b768-6d1831492432.png)

**Comment by sn4k3** [comment]
This is related to Lychee, they omit the prusaslicer.ini creation and UVtools read that file to populate some fields.
This should be reported to lychee. However printer does not need prusaslicer.ini to print the file correctly.
