### ISSUE TITLE
[Bug] -PCB exposure not showing the preview and error thrown

### ISSUE THREAD

**Issue by draj1234** [sn4k3/UVtools#692]
### System

```Text
UVtools v3.12.3 X64
Operative system: Microsoft Windows 10.0.22621 X64
Processor: Intel(R) Pentium(R) Silver J5005 CPU @ 1.50GHz
Processor cores: 4
Memory RAM: 4.70 / 7.68 GB
Runtime: win10-x64
Framework: .NET 6.0.15
AvaloniaUI: 0.10.19
OpenCV: 4.6.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100% (Primary) (On this)
    WA: 1920 x 1032    UA: 1920 x 1032


Path:       C:\Users\admin\Downloads\UVtools_win-x64_v3.12.2\
Executable: C:\Users\admin\Downloads\UVtools_win-x64_v3.12.2\UVtools.exe
Loaded file: UVtools_demo_file.sl1 [Version: 0] [Class: SL1File]
```

### Printer and Slicer

- Printer: 
- Slicer: 

### Description of the bug

Similar problem came up now !
I am using Kicad 7.0 to design and generate gerber.
But nothing is showing up in PCB exposure preview window, and also there is error as below shows up when we go for pressing the PCB exposure button.
Please help to fix this.

**Error thrown:**
System.NotImplementedException: Partial arcs are not yet implemented (G03)
To be fixed in the future...
   at UVtools.Core.Gerber.GerberFormat.ParseAndDraw(GerberFormat document, String filePath, Mat mat, Boolean enableAntiAliasing) in UVtools.Core\Gerber\GerberFormat.cs:line 411
   at UVtools.Core.Gerber.GerberFormat.ParseAndDraw(PCBExposureFile file, Mat mat, SizeF xyPpmm, MidpointRoundingType sizeMidpointRounding, SizeF offset, Boolean enableAntiAliasing) in UVtools.Core\Gerber\GerberFormat.cs:line 466
   at UVtools.Core.Operations.OperationPCBExposure.DrawMat(PCBExposureFile file, Mat mat) in UVtools.Core\Operations\OperationPCBExposure.cs:line 321
   at UVtools.Core.Operations.OperationPCBExposure.ExecuteInternally(OperationProgress progress) in UVtools.Core\Operations\OperationPCBExposure.cs:line 368
   at UVtools.Core.Operations.Operation.Execute(OperationProgress progress) in UVtools.Core\Operations\Operation.cs:line 742
   at UVtools.WPF.MainWindow.<>c__DisplayClass122_0.<RunOperation>b__0() in UVtools.WPF\MainWindow.axaml.cs:line 2121

**Kicad version used:**
Application: KiCad x64 on x64
Version: (7.0.0), release build
Libraries:
    wxWidgets 3.2.1
    FreeType 2.12.1
    HarfBuzz 5.0.1
    FontConfig 2.14.1
    libcurl/7.83.1-DEV Schannel zlib/1.2.13
Platform: Windows 11 (build 22621), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
    Date: Feb 12 2023 01:35:19
    wxWidgets: 3.2.1 (wchar_t,wx containers)
    Boost: 1.80.0
    OCC: 7.6.2
    Curl: 7.83.1-DEV
    ngspice: 39
    Compiler: Visual C++ 1934 without C++ ABI
Build settings:
    KICAD_SPICE=ON

### How to reproduce

Steps:
1.Go to tools -->PCB exposure
2.Add gerber file 
3.you cannot see any preview, it is blank
4.Now when we still go ahead to press PCB exposure - error thrown !

### Files

[UST-UWB-ESP32-BU01-BOARD-F_Cu.zip](https://github.com/sn4k3/UVtools/files/11201245/UST-UWB-ESP32-BU01-BOARD-F_Cu.zip)

**Comment by sn4k3** [comment]
Partial arcs are not implemented yet. You use 4 to do the outer board outline corner. Try to disable partial arcs on kicad so it use segments instead.

**Comment by draj1234** [comment]
> Partial arcs are not implemented yet. You use 4 to do the outer board outline corner. Try to disable partial arcs on kicad so it use segments instead.

Thanks for the reply, Can you please help to explain slightly more about "You use 4 to do the outer board outline corner." which  or what 4 ?
Also I did lot of web searching and could not find how to " disable partial arcs on kicad" Can you briefly show how to do it in Kicad I can try that.
Thanks in advance.

**Comment by sn4k3** [comment]
These are the 4 arcs:
![image](https://user-images.githubusercontent.com/113281/233472442-29e615dd-028d-42dd-84ac-c5317e1ecbc9.png)

>  Can you briefly show how to do it in Kicad I can try that.

I never used KiCAD, I don't know if that even possible, it was just a suggestion, it might not allow to disable arcs as they are better than draw curves from lines

**Comment by sn4k3** [comment]
Fixed
