### ISSUE TITLE
[Bug] ScriptTextBoxInput, ScriptCheckBoxInput, etc rendered twice

### ISSUE THREAD

**Issue by msspad** [sn4k3/UVtools#694]
### System

```Text
Version 3.13.0
```

### Printer and Slicer

- Printer: 
- Slicer: 

### Description of the bug

In the modal window "Scripting", input elements are shown twice:
![Screenshot 2023-04-25 083510](https://user-images.githubusercontent.com/6191764/234194597-a193c5b5-358c-4dff-9315-04e4ffdf4977.png)

DoubleInput.cs:
```using System;
using UVtools.Core;
using UVtools.Core.Extensions;
using UVtools.Core.Scripting;

namespace UVtools.ScriptSample;

public class DoubledInputs : ScriptGlobals
{ 
    private ScriptTextBoxInput abcInput = new() {
        Label = "abc",
        Value = ""
    };

    public void ScriptInit() {
        Script.Name = "abc";
        Script.UserInputs.Add(abcInput);
    }

    public string? ScriptValidate() {
        return "";
    }

    public bool ScriptExecute() {
        return !Progress.Token.IsCancellationRequested;
    }
}
```

### How to reproduce

Load DoubleInput.cs and run the script. Reopen the window "Scripting" again and in 80% of the cases, the input elements get rendered twice, see screenshot. So this bug does not always pop up.

**Comment by sn4k3** [comment]
I can confirm the problem.
This happens when using the restore session setting
![image](https://user-images.githubusercontent.com/113281/234315458-c931db1a-d1ac-4916-b185-4eddf86777bf.png)

**Comment by sn4k3** [comment]
Fixed
