### ISSUE TITLE
[FEATURE REQUEST] Open the app on the MAIN monitor instead of whatever monitor the desktop icon is on

### ISSUE THREAD

**Issue by ScienceofSpock** [sn4k3/UVtools#695]
### Is your feature request related to a problem?

I have 3 monitors. I keep my 3D printing-related app icons on my desktop on the right monitor. Whenever I launch UVTools, it ALWAYS starts on the right monitor. Everything else behaves properly and opens on my MAIN monitor, but not UVTools. It launches on whichever monitor the icon is on.

### Describe the solution you'd like

I would like it to open on the main monitor like virtually every other application in existence.

**Comment by sn4k3** [comment]
That is possible by using this combination of settings: 

![image](https://user-images.githubusercontent.com/113281/235219499-5c6bd8f6-2341-456c-b3b9-d1824c091ec9.png)

After save those settings, move UVtools to the screen you want, optionally maximize the window. Close UVtools and reopen, you will now have it start on that screen

**Comment by ScienceofSpock** [comment]
Except that doesn't work either, it starts BASICALLY on the right monitor, but it is not technically maximized and starts about 10 pixels to the right and I have to move it anyway.
![uvtools_offset](https://user-images.githubusercontent.com/466818/235245390-4c603011-806a-48cf-81b0-aa1591a1511a.jpg)

**Comment by sn4k3** [comment]
It works on my setup, using two different monitors.
Are you using scaling under display settings?

**Comment by ScienceofSpock** [comment]
No, I am not using scaling.

**Comment by ScienceofSpock** [comment]
I guess my real question is why does it open on the monitor where the icon is? I don't think I have ever seen desktop icon location used as a basis for which monitor to open an application on before.

**Comment by sn4k3** [comment]
No clue, the UI framework is what control that and there is no option to select starting screen as I see. Documentation says it opens on the screen where mouse is when you open the app.
I will try to combine the maximized window with other two settings to solve that.

**Comment by ScienceofSpock** [comment]
I had thought about mouse position too, and maybe I'm not fast enough, but it doesn't seem to matter. The only thing that seems to matter is where the icon is. If I put it on the left monitor, it opens on the left monitor. If I put it on the right one, it opens there.

At the end of the day, it's just a mild annoyance. Thanks for looking.

**Comment by ScienceofSpock** [comment]
Well, I just figured out a workaround. Using the settings you suggested earlier puts the window on the correct monitor, but as I mentioned, it was off by like 10 pixels. I just looked at the shortcut, and if you change the "Run" setting from the default of "Normal Window" to "Maximized" then it works! See, I had the window maximized before, but it seems you have to actually change the setting in the shortcut, at least in my situation.
