### ISSUE TITLE
[FEATURE REQUEST] - Paint tools - Flood fill, box draw, pencil size

### ISSUE THREAD

**Issue by X3msnake** [sn4k3/UVtools#7]
One thing that Validator has that is very usefull is the box paint method.
Another thing that would be very usefull would be a flood fill method.

- Box fill
- Flood fill
- Pencil tip size
- Text generator

**Comment by sn4k3** [comment]
Improve pixel edit function is on my list for the future release, including brush size and shape.
Can you explain what can be expected from Box fill and Flood fill?

**Comment by X3msnake** [comment]
Flood Fill
![flood-fill](https://user-images.githubusercontent.com/11083514/86040667-5c71fe00-ba3c-11ea-8344-7414f7959926.gif)

**Comment by X3msnake** [comment]
![box-fill](https://user-images.githubusercontent.com/11083514/86041005-e752f880-ba3c-11ea-815e-f857aeb30d9e.gif)

**Comment by sn4k3** [comment]
Thank you for details, it will be possible.
Regards

**Comment by sn4k3** [comment]
Implemented
