### ISSUE TITLE
[FEATURE REQUEST] Possibility to apply the suggestions via the command line

### ISSUE THREAD

**Issue by trev0r-STA** [sn4k3/UVtools#711]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I don't like to open the UI to do always the same task. It's too long and waste of time.
Command line is so much powerful and quicker.
So I would like to have the possibility to apply the suggestions via the command line throught a flag or something like the tool morph (for example):
- save a set of options in an .uvtools file and then apply it with the run argument of the uvtools command line utility
Thanks for your interest

### Files

No

**Comment by sn4k3** [comment]
Implemented
