### ISSUE TITLE
[FEATURE REQUEST] Expand configurability of setting in preferences to configure default file name

### ISSUE THREAD

**Issue by jbmay** [sn4k3/UVtools#725]
### Is your feature request related to a problem?

Currently after you use UVTools to modify a slice, when you go to save the file it has the default file name set to the original file name with "_copy" appended to it and there is a field to configure a file suffix.

![image](https://github.com/sn4k3/UVtools/assets/55287318/23a9ed27-d9f6-4504-9c53-bc1b5bb8b86e)

### Describe the solution you'd like

It would be nice if the field in the settings allowed more configuration how the default file name should be formatted when a file is saved. For example I would like to name the file something like the following:

![image](https://github.com/sn4k3/UVtools/assets/55287318/33c13029-585b-4903-b030-581bd42cc98c)

Where "5u_2.5s_J3D's Boxes of Calibration" was the original name of the file, "00h49m" is the calculated print time of the file, and "ready" is a literal that I want on every slice file to indicate it has gone through UV Tools and is ready to be printed.

This could be done by providing a text field in the preferences that provides some variables that users can use to define their desired default file names. An example of how a user might use this field could look like `${ORIGINAL_FILENAME}_${PRINT_TIME}_ready` where anything inside a `${}` is a variable that UVTools allows to be referenced in the field and anything outside of those is treated as a literal.

Edit: Updated to acknowledge the existing suffix setting. Request would like additional configurability.

**Comment by sn4k3** [comment]
I've added this with some more goodies:

![image](https://github.com/sn4k3/UVtools/assets/113281/36bcab26-c275-4e20-89fd-ed2a219e770b)

All public properties inside [FileFormat.cs](https://github.com/sn4k3/UVtools/blob/master/UVtools.Core/FileFormats/FileFormat.cs) can be used

**Comment by sn4k3** [comment]
Implemented, please try it

**Comment by jbmay** [comment]
Awesome thanks! Can't believe how quick you implement requested features.

**Comment by jbmay** [comment]
Tested it and confirmed it does what I was looking for!
