### ISSUE TITLE
[Bug] UV tools no longer seems to open CTB files exported from the new version of Chitubox?

### ISSUE THREAD

**Issue by Krugg66** [sn4k3/UVtools#726]
### System

```Text
UVtools v3.14.2 X64
Operative system: Darwin 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 X64
Processor: Apple M1
Processor cores: 8
Memory RAM: 3.26 / 6.15 GB
Runtime: osx.13-x64
Framework: .NET 6.0.16
AvaloniaUI: 0.10.21
OpenCV: 4.7.0

Path:       /Applications/UVtools.app/Contents/MacOS/
Executable: /Applications/UVtools.app/Contents/MacOS/UVtools
```

### Printer and Slicer

- Printer: 
- Slicer: Chitubox V1.9.5

### Description of the bug

UV tools no longer open .ctb files - with the following error, I've tried several files and none of them work. 

<img width="1271" alt="Screenshot 2023-06-11 at 18 21 40" src="https://github.com/sn4k3/UVtools/assets/136260572/65c0135f-1e96-4ece-92d9-e04696fff205">

### How to reproduce

Try to open ctb file in uv tools.

### Files

any ctb file.

**Comment by sn4k3** [comment]
Reported here: https://github.com/sn4k3/UVtools/issues/696
Will be fixed with new release
