### ISSUE TITLE
[Bug] no support 4 decimal digits (0.0255mm/25.5um)

### ISSUE THREAD

**Issue by BuyMyMojo** [sn4k3/UVtools#727]
### System

```Text
UVtools v3.14.3 X64
Operative system: Microsoft Windows 10.0.22621 X64
Processor: AMD Ryzen 5 5600X 6-Core Processor             
Processor cores: 12
Memory RAM: 17.11 / 31.93 GB
Runtime: win10-x64
Framework: .NET 6.0.16
AvaloniaUI: 0.10.21
OpenCV: 4.7.0

Sreens, resolution, working area, usable area:
1: 2560 x 1440 @ 100% (Primary) (On this)
    WA: 2560 x 1392    UA: 2560 x 1392
2: 1920 x 1080 @ 125%
    WA: 1920 x 1020    UA: 1536 x 816
3: 2560 x 1440 @ 100%
    WA: 2560 x 1392    UA: 2560 x 1392

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
```

### Printer and Slicer

- Printer: Anycubic Mono
- Slicer: Lychee 5.2.2

### Description of the bug

I print miniatures on my printer at 25.5um as it makes each layer half the pixel size but I am unable to open and modify the file in UVtools as that brings the decimal places to 4

### How to reproduce

Export at any um layer height with a decimal place (XX.X)

### Files

[PlateArmourTroop_SGT.zip](https://github.com/sn4k3/UVtools/files/11730195/PlateArmourTroop_SGT.zip)

**Comment by sn4k3** [comment]
UVtools is limited to 3 digits for layer height, and if you use 3 it will already suggest you to go at most two digits.
There is a good reason for that, most of the printers are cheap toys with a precision of 0.01mm (two digits) at best on Z (Still I don't advice be on the limit), your printer included! That means pushing more is asking for trouble and can result in visible quality problems. For example [read this](https://www.reddit.com/r/AnycubicPhoton/comments/b7ex6g/z_axis_accuracy_consistently_off_by_24/)

![image](https://github.com/sn4k3/UVtools/assets/113281/ed320fcd-f9c5-46d7-b1fe-ebb82168842d)

UVtools can work up to 3 digits and it's already 10 times more of what your printer specs for Z Precision. IMO going 3 digits even if on spec is already a bad idea, going 4 digits is a terrible idea.

This is also the reason why most slicers don't allow you to put more than 3 digits, Anycubic slicer included! (Old version only allow 2 digits)

Also layers below 0.03mm is another mistake IMO. UVtools by default recommends from 0.03mm to 0.10mm and two digits most to be on safe and best quality side.

![image](https://github.com/sn4k3/UVtools/assets/113281/55eb978c-c429-4b70-8410-8b599201d54c)

Also, the Z resolution is independent from display and you don't need an equal racio. It's all about visuals but with what you doing you risk having worse quality than going for example 0.05mm, worse than that, failed prints.

For all the above motives and the hard task of change such, I have no intentions to support more than 3 digits, when currently they are only good up to two.
