### ISSUE TITLE
[BUG] Circle overlay in pixel editor is weird

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#73]
**Describe the bug**
The overlay on mouseover is weird if the thickness of the circle is not -1 and the circle has a large diameter

**To Reproduce**
1. Enable pixel editor, Go to pixel editor tab
2. Set:
![image](https://user-images.githubusercontent.com/1091420/95680726-f882d800-0bdb-11eb-9f33-dc06c48c343f.png)

3. Mouse over in the layer holding shift
4. The mouse over is not a circle, but a square with a circle combined

The pixels are modified correctly, it is just the overlay on mouse over

**Comment by sn4k3** [comment]
That's because thinkness is draw from outside and inside model, meaning it will increase bounds. 
Cursor sets to brush size but when using thickness i should add brushsize + thickness/2

**Comment by sn4k3** [comment]
Circles are still cutting at some point, adjusting cause bad aligment with the result position. Leaving as it is for now.
