### ISSUE TITLE
[BUG] No demo file

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#75]
**Describe the bug**
Not loading the demo file

**To Reproduce**
1. Install latest
2. Open without file

Program tries to open the demo file from system32:
![image](https://user-images.githubusercontent.com/1091420/96051604-2e45ec00-0e7c-11eb-84dd-754c09dd4581.png)

**Comment by eried** [comment]
(is not that I think is important, but I saw it was on the release notes)

**Comment by sn4k3** [comment]
How do you open uvtools? run as administrator?

**Comment by eried** [comment]
No, but if I do, the result is the same.

**Comment by sn4k3** [comment]
I wonder why you pc starts uvtools on system folder...
But i will set the read file from assembly directory rather than partial

**Comment by eried** [comment]
There is no "start in" in the .lnk created by the .msi btw

**Comment by sn4k3** [comment]
Test by start uvtools from .exe on it own directory as test

**Comment by eried** [comment]
If I go to program files/ and execute the exe it works

**Comment by sn4k3** [comment]
On shortcut you can place the working directory correctly.
I wil ltry find a way to auto set it via setup and update the MSI

**Comment by sn4k3** [comment]
I reuploaded the fixed MSI.
Thanks for reporting
