### ISSUE TITLE
[Bug] Elegoo Saturn 3 Ultra - Exposure Finder Issues

### ISSUE THREAD

**Issue by IdefixRC** [sn4k3/UVtools#751]
### System

```Text
UVtools v3.15.1 X64
Operative system: Microsoft Windows 10.0.22621 X64
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor cores: 8
Memory RAM: 8.99 / 63.92 GB
Runtime: win10-x64
Framework: .NET 6.0.18
AvaloniaUI: 0.10.21
OpenCV: 4.7.0

Sreens, resolution, working area, usable area:
1: 3440 x 1440 @ 100% (Primary) (On this)
    WA: 3440 x 1392    UA: 3440 x 1392

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: UVtools_demo_file.sl1 [Version: 0] [Class: SL1File]
```

### Printer and Slicer

- Printer: Elegoo Staurn 3 Ultra
- Slicer: Chitubox V1.9.5

### Description of the bug

Test 1: 
Used known good file in .ctb format to run multi-exposure test (3 base layers, 7 Tests configured - 0.2 increments) on Saturn 3 Ultra
Ran a test print with paper on the screen. In all cases, the 3 base layers are exposed correctly.
Behavior after base layers:
Saturn 3 Ultra FW Version 1.3.9: first test is exposed, after that, the printer reports an error and stops
Saturn 3 Ultra FW Version 1.4.3 (latest): The first test is exposed fine after the base layer is printed, The printer lifts from the bed, returns back (height unknown), and then subsequently exposes the other 7 tests one by one without lifting. At the end of the 7 test lifts, return back (height unknown) and then repeat the process with the lift after the first of the 8 total tests.
Printing the test with resin results in a failure after the 3 base layers (the rest of the print stuck to the film

Test 2: 
Used known good file in .goo format to run multi-exposure test (3 base layers, 7 Tests configured - 0.2 increments) on Saturn 3 Ultra
Ran a test print with paper on the screen. In all cases, the 3 base layers are exposed correctly.
Behavior after base layers:
Saturn 3 Ultra FW Version 1.4.3 (latest): The first test is exposed fine after the base layer is printed, the printer lifts from the bed, returns back (height unknown), and then subsequently exposes the other 7 tests one by one **but with a minor lift increment** - can see the ball screw just slightly twitching between each. At the end of the 7 test lifts, return back (height unknown) and then repeat the process with the lift after the first of the 8 total tests.
No resin test was done as it would surely fail as each of the 7 tests after the first had a slightly higher z height.

Maybe I'm doing something wrong in the settings??

### How to reproduce

see above

**Comment by sn4k3** [comment]
On recent machines using new CTB format users are getting problem with the this test. I don't know if is something that must be set on file or if is the firmware.

Bottom layers always print fine because they are printed like regular model and all at once. Problems starts when it attempt to print new layers on same previous layer Z.

It's normal to see a small lift as there are no way to remove them (it not accept 0 as lift).

For goo you have also to test with resin, the fact that you observed the same thing don't mean it will fail too. So I recommend at least one try.
