### ISSUE TITLE
[Bug] Strange behaviour of holes after moving objects  

### ISSUE THREAD

**Issue by tecchese** [sn4k3/UVtools#752]
### System

```Text
UVtools v3.15.1 X64
Operative system: Microsoft Windows 10.0.19045 X64
Graphic card: 
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Processor cores: 8
Memory RAM: 5.88 / 15.89 GB
Runtime: win10-x64
Framework: .NET 6.0.18
AvaloniaUI: 0.10.21
OpenCV: 4.7.0

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: gommino passacavo_gommino.pwma [Version: 516] [Class: PhotonWorkshopFile]
```

### Printer and Slicer

- Printer: Photon mono 4k
- Slicer: Lichee

### Description of the bug

Hallo, maybe there is a strange issue when moving object over the screen, it seems the holes are not moved correctly together with the objects.
Furthermore it seems the price of the used material is not calculated correctly.
Thank you for your support.

### How to reproduce

![Immagine 2023-09-04 191822](https://github.com/sn4k3/UVtools/assets/107458958/8670d792-e539-4227-8670-b3859584c069)

**Comment by sn4k3** [comment]
That's because the issues are not recalculated. You need to recalculate the issues to update their position. Everything that is colored is virtual and do not represent the model, there before does not affect it

**Comment by sn4k3** [comment]
Fixed with issue recalculation
