### ISSUE TITLE
[FEATURE REQUEST] extract thumbnail.

### ISSUE THREAD

**Issue by bartoszek** [sn4k3/UVtools#754]
### Is your feature request related to a problem?

I would like to write a thumbnailer for a Linux desktop, and need an option to quickly extract a thumbnail or a specific layer from the sliced file. 

### Describe the solution you'd like

Add option `get-thumbnail` `get-layer -id #` to `UVtoolsCMD` or a switch to `extract` command `--layer=#` `--thumbnail`

**Comment by sn4k3** [comment]
Implemented
