### ISSUE TITLE
[Bug] OSX - Can not open uvtools

### ISSUE THREAD

**Issue by apertureless** [sn4k3/UVtools#764]
### System

```Text
Macbook Air M2 - OSX Ventura 13.6
```

### Printer and Slicer

- Printer: 
- Slicer: 

### Description of the bug

Installed uvtools over homebrew but also tried the app from github releases.
If I try to open it, I get a error message from osx:

"The program "UvTools" can't be opened.

### How to reproduce

1. Install
2. Try to launch

**Comment by sn4k3** [comment]
For macOS must be installed with my installation script, see here: https://github.com/sn4k3/UVtools#to-auto-install-on-macos

**Comment by apertureless** [comment]
But it is available over homebrew, too.

Anyways thanks, the installation script gave me the fix.
If anyone else is installing directly over homebrew

```
codesign --force --deep --sign - /Applications/UVtools.app
```

will fix this.

**Comment by sn4k3** [comment]
In past macOS allowed to run "untrusted/not certified" apps and so homebrew installations worked, but not anymore. Unfortunately, homebrew does not allow us to run self-certification scripts (Security)
