### ISSUE TITLE
[Improvement] Change HotKey from Control to Command under macOS

### ISSUE THREAD

**Issue by Hazoooka** [sn4k3/UVtools#766]
### System

```Text
UVtools v4.0.1 X64
Operative system: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 X64
Processor: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
Processor cores: 24
Memory RAM: 7.14 / 24.03 GB
Runtime: osx.10.15-x64
Framework: .NET 6.0.22
AvaloniaUI: 11.0.4
OpenCV: 4.8.0

Path:       /Users/witos/Applications/UVtools.app/Contents/MacOS/
Executable: /Users/witos/Applications/UVtools.app/Contents/MacOS/UVtools
```

### Printer and Slicer

Mac OS version lacks a possibility to use standard system keys.
In Mac OS there is "Command" key instead of "Control" being used.
Important program functions are triggered with the Command key in combination with others.
In Windows this is handled by the Control key.
Lack of the support for the Command key cripples the program quite a bit.

Please add the Command key in the Mac version as a default one, with a possibility to switch to Control key in the settings.

Kind reagards,
Witold.

### Description of the bug

Whenever I press Command+S keys I do not have any action. It is supposed to save the file.
All the functions in the program that should work do not.
Mac OS's workflow is based on the Command key.

### How to reproduce

Opend the file and try to save using the combination of Command+S keys.

**Comment by sn4k3** [comment]
Implemented

**Comment by Hazoooka** [comment]
Thank you.
