### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BblackmilkK** [sn4k3/UVtools#767]
### System

```Text
UVtools v4.0.2 X64
Operative system: Microsoft Windows 10.0.22621 X64
Processor: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Processor cores: 12
Memory RAM: 11.76 / 31.94 GB
Runtime: win10-x64
Framework: .NET 6.0.22
AvaloniaUI: 11.0.4
OpenCV: 4.8.0

Sreens, resolution, working area, usable area:
1: 2560 x 1440 @ 100% (Primary) (On this)
    WA: 2560 x 1392    UA: 2560 x 1392

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: 3lu x.pm3m [Version: 516] [Class: PhotonWorkshopFile]
```

### Printer and Slicer

- Printer: m3 max / sonic mega 8k / mono x
- Slicer: chitubox pro

### Description of the bug

There are 2 different dimensions. What is this ?

### How to reproduce

re install (clean)

### Files

![1](https://github.com/sn4k3/UVtools/assets/106093498/ec8c9dc2-0dcf-49aa-bb8b-16414c65de39)
![2](https://github.com/sn4k3/UVtools/assets/106093498/52b0380e-78b4-40b2-bd0b-4a4eb5fb95c8)

**Comment by BblackmilkK** [comment]
![1b](https://github.com/sn4k3/UVtools/assets/106093498/3e4716c6-c95b-4f05-bc1c-f4b4f4135a0a)
![1a](https://github.com/sn4k3/UVtools/assets/106093498/a67827b8-f8a7-403c-933f-82eaac9fd8a2)

**Comment by sn4k3** [comment]
I don't get it, what is exactly the question?
