### ISSUE TITLE
[Bug] Converting from Prusa Slicer to .prz format cause stall of the printer

### ISSUE THREAD

**Issue by ecospline** [sn4k3/UVtools#776]
### System

```Text
UVtools v4.0.3 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz
Processor cores: 28
Memory RAM: 8.74 / 31.92 GB
Runtime: win10-x64
Framework: .NET 6.0.23
AvaloniaUI: 11.0.5
OpenCV: 4.8.0

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: UVtools_demo_file.sl1 [Version: 0] [Class: SL1File]
```

### Printer and Slicer

- Printer: Phrozen Sonic Mini 8K S
- Slicer: Prusa Slicer 2.6.1

### Description of the bug

Conversion of a .sl1 file from Prusa Slicer 2.6.1 to .prz format using specyfic converter cause of stalling the printer at the begining of the print. The platform of the printer goes down to prepare for the first layer, and than it stalls - sometimes LCD turns on and it'e lit the whole area, sometimes it shows first layer but it looks corrupt (lot of irregular horizontal lines), sometimes LCD is just black and sometimes - after a while from stalling the message of an error appears with information "Error! Printing file data exception!". 
![01_Error info](https://github.com/sn4k3/UVtools/assets/67028508/1a5c76d6-66fc-4063-816b-7c9194c8ce1b)

### How to reproduce

1. Prepare file in Prusa Slice 2.6.1 , slice it and export in .sl1 format 
2. Open .sl1 file ion UVTools 
3. Convert the file to .prz format to gain acces to the whole parameters of the print (Edit Parameters in UV tools) 
I have changed: 
- Bottom layers  [value= 24]
- Wait after cure (bottom) [value= 1]
- Lift height (bottom)  [value= 2>3 ]
- Lift speed (bottom)  [value= 50>70 ]
- Retract speed (bottom) [value= 70>60 ]
- Retract height (bottom) [value= .....>3 ]
- Transition layers [value= 7]
- Exposure time [value= 1.4]
- Wait after cure [value= 0.2]
- Lift height [value= 2>3 ]
- Lift speed [value= 70>90 ]
- Retract speed [value= 100>80 ]
- Retract height [value= .....>2 ]

4. Change parameters of the print
5. Save file (overwrite .prz file) 
6. Save final file on Phrozens USB stick 
7. Try to print the file...

**Comment by sn4k3** [comment]
Can provide the file?

**Comment by sn4k3** [comment]
Fixed
