### ISSUE TITLE
[Bug] Incorrect Material Cost Calculation

### ISSUE THREAD

**Issue by TRusselo** [sn4k3/UVtools#780]
### System

```Text
UVtools v4.0.3 X64
Operative system: Microsoft Windows 10.0.22621 X64
Processor: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
Processor cores: 16
Memory RAM: 12.93 / 15.92 GB
Runtime: win10-x64
Framework: .NET 6.0.23
AvaloniaUI: 11.0.5
OpenCV: 4.8.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100%
    WA: 1920 x 1032    UA: 1920 x 1032
2: 3840 x 2160 @ 100%
    WA: 3840 x 2112    UA: 3840 x 2112
3: 5120 x 1440 @ 100% (Primary) (On this)
    WA: 5120 x 1392    UA: 5120 x 1392

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: phone_holeder_top_nut_scr_05h23m_108ml_copy.ctb [Version: 0] [Class: CTBEncryptedFile]
```

### Printer and Slicer

- Printer: Mars 3 Pro (im sorry)
- Slicer: Lychee 5.4.002 (ashamed)

### Description of the bug

UVTools Material Cost $1.400,628.38
Lychee Material Cost $5.60 CAD

![image](https://github.com/sn4k3/UVtools/assets/1154815/de0347f9-9f73-4167-aba9-8c645cdb2268)

### How to reproduce

Edit file in Lychee, click "calculate resin volume" in lower left corner, says CAD $5.60
export slices to file
Open with UVtools (by clicking button in Lychee)
Apply Suggestions ( ? unsure  if required )

Noticed 1.4 million dollars at bottom of UV TOOLS

### Files

[phone_holeder_top_nut_scr (2).zip](https://github.com/sn4k3/UVtools/files/13246371/phone_holeder_top_nut_scr.2.zip)
[phone_holeder_top_nut_scr_06h08m_108ml_copy.zip](https://github.com/sn4k3/UVtools/files/13246372/phone_holeder_top_nut_scr_06h08m_108ml_copy.zip)

ctb files compressed to rar, then zipped

zip could  not compress enough,
rar not supported.
sorry for the extra clicks, i promise nothing sketchy.

**Comment by sn4k3** [comment]
Not the first time I see such issue. It looks like a lychee bug when writing the file. If you look at properties of the file you can find that value. Note that values are only updated by UVtools when you save the file, before that what you see comes directly from slicer.

**ie: try to slice same file on Chitubox and open in UVtools.** 

![image](https://github.com/sn4k3/UVtools/assets/113281/8f11bd3c-82d0-4a9b-a263-b39ac4b3ab01)
