### ISSUE TITLE
Change infill to detect "roofs" and "floors"

### ISSUE THREAD

**Issue by frank-vanderhulst** [sn4k3/UVtools#785]
### Is your feature request related to a problem?

Infill does not detect intermediate horizontal "roofs" or "floors" in the model. 

It leaves a solid "floor" from 0 to the specified "from" layer, and a solid "roof" from the specified "to" layer to the top of the model, and it generates solid walls of the requested thickness. However, if there is a horizontal surface larger than (wall thickness * 2) below the top layers it does not leave it as a solid layer, so that the infill is visible. In the example files, see layer 826 and 1156.

This only applies to horizontal (or nearly horizontal) layers. Sloping layers are visually OK so long as the wall of one layer overlaps the wall of the next. However, their walls may be quite thin. e.g. in the extreme case where the slope of a wall is 1 in "wall thickness", the thickness of the wall, orthogonal to the slope, will be only 1 pixel.

### Describe the solution you'd like

Quick solution:
Detect horizontal surfaces larger than (2 * wall thickness) in both X & Y dimensions and leave them solid for "wall thickness" layers.

Better solution:
Change the calculation of wall thickness to a 3D model, so that walls are the same thickness, no matter what slope they're at.

### Files

[E.zip](https://github.com/sn4k3/UVtools/files/13260652/E.zip)
![20231106_085604](https://github.com/sn4k3/UVtools/assets/97711900/a53038a3-e2ac-4c01-ac35-8503de532a8e)

**Comment by sn4k3** [comment]
Implemented
