### ISSUE TITLE
[BUG] Installer should "update" previous installer

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#79]
Hi, for some reason the installer is going over the old installer. It should upgrade, or remove the previous installation:
![image](https://user-images.githubusercontent.com/1091420/97079807-134f4680-15f7-11eb-894a-d5c757b19955.png)

**Comment by eried** [comment]
(I think the reason is because all installers are using 0.0.1 as the version and maybe not keeping same guid?)

**Comment by sn4k3** [comment]
I'm aware of it. All properties and GUIDs are all the same in all releases, only changes the files. This MSI packages and coding are a pain...

**Comment by sn4k3** [comment]
i think i got it, next release please remove all uvtools from programs first to clear it out

**Comment by eried** [comment]
Great!

**Comment by sn4k3** [comment]
Fixed
