### ISSUE TITLE
[Bug] Invalid ctb file and failed import to chitubox

### ISSUE THREAD

**Issue by jpdore15** [sn4k3/UVtools#791]
### System

```Text
UVtools v4.0.4 X64
Operative system: Microsoft Windows 10.0.22631 X64
Processor: Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
Processor cores: 12
Memory RAM: 5.81 / 7.83 GB
Runtime: win10-x64
Framework: .NET 6.0.24
AvaloniaUI: 11.0.5
OpenCV: 4.8.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 125% (Primary) (On this)
    WA: 1920 x 1020    UA: 1536 x 816

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: UVtools_demo_file.sl1 [Version: 0] [Class: SL1File]
```

### Printer and Slicer

- Printer:  Elegoo Saturn Ultra 3
- Slicer:  Chitubox Basic v1.9.5

### Description of the bug

After opening a valid sliced file from Chitubox, and run the test calibration, exposure time finder and save as a new .ctb file I get an invalid file when trying to open the new file in Chitubox. If I then select the "export" option for for the ctb file and then open it does seem to open. 

If I try to do the same thing with the advanced options checked and export the same way the file does not seem to be layered correctly in chitubox.

Attached are a few images from chitubox

![invaild file](https://github.com/sn4k3/UVtools/assets/89335556/31b71ee3-0cee-4ed6-9932-fdb4230b828e)
![single file v4](https://github.com/sn4k3/UVtools/assets/89335556/f20043ca-e64b-4b47-bbd1-7f2b447b5ce5)
![v3](https://github.com/sn4k3/UVtools/assets/89335556/157c8217-fd62-497e-9843-79e92bf7a663)
![v4 ](https://github.com/sn4k3/UVtools/assets/89335556/fc15a2d2-27e5-4a78-a9ad-f93854dfaa7a)

### How to reproduce

Issue 1:
Opened sliced ctb file
ran exposure time finder
saved as new ctb
fails to open in chitubox.

Issue 2:
Opened sliced ctb file
ran exposure time finder and selected advanced options
saved as new ctb and then exported as ctb file
opened in chitubox but file is not correct

### Files

[test calibration multi files.zip](https://github.com/sn4k3/UVtools/files/13452989/test.calibration.multi.files.zip)

**Comment by sn4k3** [comment]
Any file with multiple layers in same z position will never render correct in chitubox, this is with their software as it does not expect nor built to support more than 1 layer in given position.
