### ISSUE TITLE
Pixel Edit - Brush diameter locks at 7px and can't be reduced after a few edits and "Apply All" performed

### ISSUE THREAD

**Issue by viperman3** [sn4k3/UVtools#80]
While manually performing Pixel Edit with Brush Shape set to Circle, the Brush diameter get's locked at 7px and cant be reduced to a lower number.

Is this the intended minimum size of the circle brush (7px)?

**Comment by sn4k3** [comment]
Yes, because circle is only a circle with 7px or higher, so its locked to 7 minimum.
If you select rectangle you can go back to 1px

**Comment by sn4k3** [comment]
Normal behaviour
