### ISSUE TITLE
Material cost 

### ISSUE THREAD

**Issue by MikeOxawopper** [sn4k3/UVtools#801]
### System

```Text
UVtools v4.0.5 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Processor cores: 8
Memory RAM: 10.69 / 15.95 GB
Runtime: win10-x64
Framework: .NET 6.0.25
AvaloniaUI: 11.0.6
OpenCV: 4.8.1

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: Main Engine Bell.pwma [Version: 516] [Class: PhotonWorkshopFile]
```

### Printer and Slicer

- Printer: Anycubic Photon Mono 4k
- Slicer: Lychee

### Description of the bug

Price per 1000ml is either euro or dollar?
Displayed cost per model is in GBP
Actual displayed cost is miles out? 
Bottle cost 25 per 1000ml
Part usage 6ml part cost 6 pounds sterling?  that makes cost per ML 1 pound which means the software thinks a 1000ml bottle cost a 1000 pounds?
![uv cost](https://github.com/sn4k3/UVtools/assets/65547160/d3c53429-64c5-4ab2-b476-ba8fb0232508)

### How to reproduce

load file

**Comment by sn4k3** [comment]
In UVtools settings is displayed as €.
In status bar is show as configured on your OS regional symbol, which in your case is £.
Either are just a representative of currency and it doesn't matter for the program -- it does not do any conversions.
As so, just input the raw value in your currency. Ie: If you pay 20 £ per a 1000ml bottle, input in UVtools settings "20".

However, that setting is only for files that lack the price information to be able to compute a price estimate. That is not the case with Anycubic files and so such setting is unused. It come from slicer which in your case lychee, and as other reported it's a bug where is set incorrectly there. UVtools just loads and display the value, and scale it accordingly if you add or remove pixels.
Remember that UVtools is not the slicer, in firsthand it loads all data from a sliced generated file, as so most if not all in some cases of the information you see was set by slicer and not UVtools.

See similar issue: https://github.com/sn4k3/UVtools/issues/780

To test the theory of slicer, do same slicing on Chitubox and open in UVtools, see what value you got and report back.
