### ISSUE TITLE
System.NullReferenceException when stack importing layers since the 4.2.0 update

### ISSUE THREAD

**Issue by Darantius** [sn4k3/UVtools#835]
### System

```Text
UVtools v4.2.0 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Processor cores: 4
Memory RAM: 6.86 / 15.93 GB
Runtime: win10-x64
Framework: .NET 6.0.26
AvaloniaUI: 11.0.7
OpenCV: 4.8.1

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: PRINT 102% Metal floor arrow tip maghex.pwmx [Version: 1] [Class: PhotonWorkshopFile]
```

### Printer and Slicer

- Printer: Anycubic Photon Mono X
- Slicer: Lychee

### Description of the bug

Since the most recent update, importing layers using the 'stack' method (to add an existing model next to another) often generates this error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationLayerImport.<>c__DisplayClass61_5.<ExecuteInternally>b__4(Int64 i) in UVtools.Core\Operations\OperationLayerImport.cs:line 518
   at System.Threading.Tasks.Parallel.<>c__DisplayClass20_0`1.<ForWorker64>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass20_0`1.<ForWorker64>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

### How to reproduce

1. Open sliced object 'A' in UVtools, detect issues and resolve, save file, close
2. Open sliced object 'B' in UVtools, detect issues and resolve, save file
3. Use import layers function with 'stack' method to try to add save object A next to B (or other way around) to be printed together.
4. Error returned after import calculation. Object not added

I've attached two files as an example which most recently caused this issue. Have seen the issue with many other files however.

### Files

[Import bug example files.zip](https://github.com/sn4k3/UVtools/files/14203091/Import.bug.example.files.zip)
![UVtools_mRWtPafUJp](https://github.com/sn4k3/UVtools/assets/139199830/be449613-41a7-46bd-96a0-a05890d9b86b)
![UVtools_y34kzUmgkX](https://github.com/sn4k3/UVtools/assets/139199830/eeefeaae-ac16-4afe-8554-a59ee16b931c)

**Comment by sn4k3** [comment]
Fixed
