### ISSUE TITLE
[BUG] Can not open Chitubox sliced .cws files

### ISSUE THREAD

**Issue by Klausxdy** [sn4k3/UVtools#84]
Hi,

As my title said. File and screenshot attached. Thank you!

![bb75856baa179d522b3f12e2fedd982](https://user-images.githubusercontent.com/63583796/97579598-26448b00-19ea-11eb-835d-7877c3476554.png)
[_cube.zip](https://github.com/sn4k3/UVtools/files/5458596/_cube.zip)

**Comment by sn4k3** [comment]
Will fix on next patch

**Comment by sn4k3** [comment]
Fixed
