### ISSUE TITLE
[FEATURE REQUEST]  support for new ANYCUBIC file format for Anycubic Photon Mono M5s Pro - *.m5sp

### ISSUE THREAD

**Issue by zaphod71** [sn4k3/UVtools#842]
### Describe the solution you'd like

support for new file format

**Comment by sn4k3** [comment]
UVtools already support **pm5s**

**Comment by zaphod71** [comment]
Hi, you're right. I got the two mixed up. It is the format with the extension *.m5ps

**Comment by sn4k3** [comment]
Implemented
