### ISSUE TITLE
[Bug] System.IO.FileLoadException: The file checksum does not match, malformed file

### ISSUE THREAD

**Issue by farcast3r** [sn4k3/UVtools#845]
### System

```Text
UVtools v4.2.4 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Processor cores: 8
Memory RAM: 13.62 / 31.93 GB
Runtime: win10-x64
Framework: .NET 6.0.27
AvaloniaUI: 11.0.7
OpenCV: 4.8.1

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100% (On this)
    WA: 1920 x 1040    UA: 1920 x 1040
2: 1920 x 1080 @ 100% (Primary)
    WA: 1920 x 1040    UA: 1920 x 1040

Path:       C:\Users\Jake\Downloads\UVtools_win-x64_v4.2.4\
Executable: C:\Users\Jake\Downloads\UVtools_win-x64_v4.2.4\UVtools.exe
```

### Printer and Slicer

- Printer: ELEGOO Mars Ultra 4K
- Slicer:  Chitubox Basic 2.0

### Description of the bug

I sliced a model in Chitubox but I get this error when trying to import the sliced file into UVtools:
![image](https://github.com/sn4k3/UVtools/assets/156135703/8ff4191e-ee1a-4c3d-90a4-4c0cd0523341)

### How to reproduce

Import sliced file (attached)
[squirtle.stl_0.05_2.5_2024_03_06_16_07_0033.ctb.zip](https://github.com/sn4k3/UVtools/files/14512597/squirtle.stl_0.05_2.5_2024_03_06_16_07_0033.ctb.zip)

**Comment by Vergotear** [comment]
I have the same checksum issue for CTB files sliced with Chitubox Basic 2.0 for Saturn 2 or Mars 4 Ultra as the OP.

**Comment by mostovskiy** [comment]
Same here. Elegoo Saturn 2 and Chitubox Basic 2.0

**Comment by rhom6us** [comment]
Same here. Elegoo Saturn 2 and Chitubox Basic 2.0

**Comment by robertorocca** [comment]
Same here too. Elegoo Mars3 and Chitubox basic 2.0
