### ISSUE TITLE
[Bug]  Photon Mono M5s Pro incorrect display height and width in PhotonWorkshopFile.cs

### ISSUE THREAD

**Issue by dbcook** [sn4k3/UVtools#858]
### System

```Text
Any
```

### Printer and Slicer

Anycubic Photon Mono M5s Pro

### Description of the bug

In PhotonWorkshopFile.cs, the display height/width values are wrong.  It is not 218x223mm (we could wish!)

See https://wiki.anycubic.com/en/resin-3d-printer/photon-mono-m5s-pro for official values of 223.78 x 126.38

### How to reproduce

examine source code

**Comment by sn4k3** [comment]
Will fix on next patch.
However that values are never used, they are fetch from file format instead, so no potential problem from this bug.

**Comment by sn4k3** [comment]
Fixed
