### ISSUE TITLE
[FEATURE REQUEST] Add sound when done Computing issues

### ISSUE THREAD

**Issue by sbrevolution5** [sn4k3/UVtools#863]
### Is your feature request related to a problem?

It can take a long time to run the issue computation/fix, utility, and I usually go and do something else while its running.  

### Describe the solution you'd like

It would be very convenient if we could have the option to have a chime or ding of some sort play when the issues are finished being detected and fixed.  I understand this is such a small concern, but its a potential improvement.

**Comment by sn4k3** [comment]
Cross platform audio engine are heavy and add some dependencies, just to support this is a bit of non-sense.
However if it help I can add native notifications, that itself produce a sound from OS if not muted. 

Are you on Windows?

**Comment by sbrevolution5** [comment]
That would definitley be a solution!  Understandable that implementing a whole audio engine wouldn’t be worth itOn Apr 9, 2024, at 2:23 PM, Tiago Conceição ***@***.***> wrote:﻿
Cross platform audio engine are heavy and add some dependencies, just to support this is a bit of non-sense.
However if it help I can add native notifications, that itself produce a sound from OS if not muted.
Are you on Windows?

**Comment by sn4k3** [comment]
This have to be delayed. Using notifications requires at least Windows 10, version 1809 TFM which will exclude Windows 7 from working with UVtools, I'm not interested in keep two separate builds for windows.
Drop the support for Windows 7 is expected when transiting to net8.0 in next major of UVtools (v5).

**Comment by sn4k3** [comment]
I come to this:

![image](https://github.com/sn4k3/UVtools/assets/113281/bef68e72-bed9-4348-abf9-562034fccceb)

Works under Windows & Linux. For mac it will play system invalid beep (No frequency nor duration able)

**Comment by sn4k3** [comment]
Implemented
