### ISSUE TITLE
[FEATURE REQUEST] Cant select inverse range

### ISSUE THREAD

**Issue by mylife4aiurr** [sn4k3/UVtools#87]
## Is your feature request related to a problem? 
The problem is elephant foot, the layers that get over exposed. i want to start at top layer of bottom layer and apply a given function towards first layer. So 8 to 0, instead of 0 to 8. (example of bottom layer range)

## Describe the solution you'd like
I'd like to start at the highest layer of the bottom layers applying function towards zero layer. Say bottom layers are 0 to 8 - example. To create a chamfer, so thickest layer is 8 and thinest is 0 and then slope is what user chooses in function (morph erode). This cant be done currently, UVtools errors.

**Comment by sn4k3** [comment]
I think what you are asking is already implemented, you can do chamfers with the Fade option, try:

![image](https://user-images.githubusercontent.com/113281/97807329-1336f280-1c58-11eb-9295-2850c96af751.png)

That will erode from 8 to 1

**Comment by mylife4aiurr** [comment]
Thank you sir, I will give it a try. Didnt try the fade option.
