### ISSUE TITLE
Strange yellow text while resetting morph values 

### ISSUE THREAD

**Issue by tecchese** [sn4k3/UVtools#872]
### System

```Text
UVtools v4.3.2 X64
Operative system: Microsoft Windows 10.0.19045 X64
Graphic card: 
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Processor cores: 8
Memory RAM: 8.76 / 15.89 GB
Runtime: win10-x64
Framework: .NET 6.0.29
AvaloniaUI: 11.0.10
OpenCV: 4.8.1

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: unnamed_unnamed (1)_unnam.px6s [Version: 517] [Class: PhotonWorkshopFile]
```

### Printer and Slicer

- Printer:  Anycubic Photon Mono 6kps
- Slicer:  Lychee Slicer

### Description of the bug

Hallo, it is a minor bug, maybe it will be simple to fix (see attached snapshot)

### How to reproduce

Just select Morph tool, delete the existing value and the issue will appear (see pic)

### Files

![Immagine 2024-05-07 184517](https://github.com/sn4k3/UVtools/assets/107458958/fda0559c-d491-4ec4-b7d2-f1684f4188ab)

**Comment by sn4k3** [comment]
That happen everywhere where you have an numeric inputbox and you delete all text. Is part of UI framework validations.
