### ISSUE TITLE
[FEATURE REQUEST] Mac OS build

### ISSUE THREAD

**Issue by sandrobilbeisi** [sn4k3/UVtools#89]
## Mac OS Build
Recent versions of Visual Studio allow to compile C# project for the Mac OS platform.

Is someone interested in venturing in a Mac OS build ?

**Comment by sn4k3** [comment]
UVtools already run on MacOS, just download the zip binaries and follow readme on Mac section.

**Comment by sandrobilbeisi** [comment]
I meant as a standalone , not as a homebrew install ...

**Comment by sn4k3** [comment]
That's possible by simple compile the runtime and deploy as MacOS.
I can support that in a future, i'm not yet because that require a deploy for each system and version and not universal package anymore
