### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thirstyone** [sn4k3/UVtools#893]
### System

```Text
UVtools v4.3.2 X64
Operative system: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 X64
Processor: Intel(R) Core(TM) i7-2675QM CPU @ 2.20GHz
Processor cores: 8
Memory RAM: 8.13 / 13.90 GB
Runtime: osx.13-x64
Framework: .NET 6.0.29
AvaloniaUI: 11.0.10
OpenCV: 4.8.1

Sreens, resolution, working area, usable area:
1: 1440 x 900 @ 100% (Primary)
    WA: 1440 x 875    UA: 1440 x 875

Path:       /Applications/UVtools.app/Contents/MacOS/
Executable: /Applications/UVtools.app/Contents/MacOS/UVtools
Loaded file: UVtools_demo_file.sl1s [Version: 0] [Class: SL1File]
```

### Printer and Slicer

- Printer: 
- Slicer: 

### Description of the bug

See attached gerber to pdf and gerber to uvtools, why the oval pads? 
![Screenshot 2024-06-26 at 12 28 04](https://github.com/sn4k3/UVtools/assets/1595242/a07be8ec-3d28-46b2-90ac-b85fb31c565e)

### How to reproduce

Tools-PCB exposure

**Comment by sn4k3** [comment]
Was that applied to UVtools startup demo file?
Please upload the gerber so I can check.
Also fill in the information:

Printer: 
PCB Software:
