### ISSUE TITLE
[BUG] Too long windows in settings with 125% scaled screen

### ISSUE THREAD

**Issue by MarkusReichart** [sn4k3/UVtools#90]
In the settings of version 1.1.2 the windows of the tabs "Layer preview" and "Issues" are too long to be fully displayed on a 125% scaled screen.

**Comment by sn4k3** [comment]
Zoom overrides are always a problem. Can you send a screenshot?

**Comment by MarkusReichart** [comment]
![Screenshot 2020-11-03 203124](https://user-images.githubusercontent.com/52602624/98032583-81281900-1e14-11eb-90c7-2dceefa35a97.png)
![Screenshot 2020-11-03 203646](https://user-images.githubusercontent.com/52602624/98032590-84230980-1e14-11eb-971b-587509fa10f2.png)

Dont be confused. I have a dual screen setup and stared uvtools twice. full screen on each displaz

**Comment by sn4k3** [comment]
ok i see the problem, the uvtools windows are height resolution dependent to set the scroll bar and window max height but there are no zoom setting available on this framework to fix this :(

**Comment by sn4k3** [comment]
fixed
