### ISSUE TITLE
[BUG] UVtools finds island thats supported

### ISSUE THREAD

**Issue by jarjo** [sn4k3/UVtools#92]
## Describe the bug
Indicates that an island that is supported is unsupported

## To Reproduce
1. open file
2. Click on issues
4. Island reported on layer 1461 but support visible on 1460 

## Screenshots
If applicable, add screenshots to help explain your problem. Never hide information, full GUI/window screenshot is always a must!
![layer1461](https://user-images.githubusercontent.com/46713086/98104282-829a2580-1e96-11eb-9727-446befc004d9.png)
![layer1460](https://user-images.githubusercontent.com/46713086/98104285-8332bc00-1e96-11eb-8b77-a60471f2f0ce.png)

## Files
Were possible attach the problematic file, both source and output file if applicable.
[island_error.zip](https://github.com/sn4k3/UVtools/files/5487403/island_error.zip)

## System
Desktop (please complete the following information):
Win 10 x64 version 10.0.18363

**Comment by sn4k3** [comment]
Read this: https://github.com/sn4k3/UVtools/releases/tag/v0.8.6.0

**Comment by jarjo** [comment]
that explains it thanks
